#!/usr/bin/env python3
"""
Electric Wizard - Dopethrone (Recreation)
=== a FAITHFUL recreation of a real doom song, written in the compose_doom_*.py idiom ===

Auto-generated by transcribe_song.py / analysis.extract_blocks from the Guitar Pro tab,
then iterable like compose_doom_drowned_cathedral.py. Each lane is expressed as named,
reusable BLOCKS (riffs / grooves / pedals / rests) plus a flat SONG MAP -- a
`[(block, count), ...]` score that cycles those blocks to rebuild the whole part. Tweak
a block, or re-order / re-count a song map, to spin a new piece off this structure.

  Key/feel : Bb minor blues, 55 BPM, 149 bars / 596 beats
  Lanes    : lead=distortion-guitar, rhythm=distortion-guitar, bass=electric-bass-pick, drums=drum-kit

FAITHFUL on pitch, voicing, rhythm, every drum hit, the tempo map and the arrangement.
NOT reproduced: per-note velocity (absent from the source IR -> flat) and notated meter
changes (kept as a global 4/4 -- audio is unaffected since durations are absolute beats).
"""

import sys
from pathlib import Path

REPO = Path(__file__).parent
sys.path.insert(0, str(REPO))

from skills.generate_midi import generate_midi_from_dict, parse_duration


def ln(s):
    """Compact "P:dur P:dur ..." note string -> [('pitch', 'duration'), ...].

    `P` is a pitch (`B1`), a chord (`B2+Gb3+B3`), a drum name, or a rest (`R`);
    `dur` is a skill duration token (`2`, `d4`, `T8`). Whitespace-separated, so a
    block that took dozens of dict lines is one readable string here.
    """
    return [dict(zip(("pitch", "duration"), t.rsplit(":", 1))) for t in s.split()]


def expand(blocks, score):
    """A lane's [(block_name, count), ...] song map -> a flat list of note dicts."""
    out = []
    for name, count in score:
        out += blocks[name] * count
    return out


def beats(notes):
    return sum(parse_duration(n["duration"]) for n in notes)


# ===================== LEAD blocks (distortion-guitar) =====================
LEAD = {
    "REST": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "RIFF_A": ln(
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8 Ab1:16 "
        "Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8"),   # 2 bar(s), 24 events
    "RIFF_B": ln(
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 "
        "Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 "
        "Eb1:16 Eb1:16"),   # 2 bar(s), 28 events
    "RIFF_C": ln(
        "Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 "
        "Bb0:16 Db1:16 D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 "
        "Eb1:d8 Eb1:16 Eb1:16 Eb1:16 E1:d8 E1:16 E1:16 E1:16 Db1:16 Db1:16 Db1:8"),   # 4 bar(s), 38 events
    "RIFF_D": ln(
        "Bb1:4 Bb1:8 Bb1:16 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 "
        "F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:16 Db2:16 Ab1:16 Ab1:16 Bb1:4 Bb1:8 Bb1:16 Bb1:8 "
        "Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 "
        "F1:16 Db1:8 Db2:16 Db2:16 Ab1:16 Ab1:16"),   # 4 bar(s), 48 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST3": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
}

LEAD_SCORE = [
    ("REST", 1), ("RIFF_A", 2), ("RIFF_B", 2), ("RIFF_C", 2), ("RIFF_D", 2), ("REST2", 7),
    ("REST3", 1), ("REST4", 1),
]

# ===================== RHYTHM blocks (distortion-guitar) =====================
RHYTHM = {
    "RIFF_A": ln(
        "Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 "
        "E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 "
        "Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 "
        "Eb2:16 Eb2:8"),   # 4 bar(s), 40 events
    "RIFF_B": ln(
        "Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 "
        "E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 "
        "Eb2:16 Eb2:8 Db2:16 Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:8 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:8 Db2:16 "
        "Eb2:16 Eb2:8 Bb1+Bb2:8 Bb1+Bb2:16 Bb1+Bb2:16 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 "
        "Eb2:16 Eb2:16 Eb2:16 Bb1+Bb2:8 Bb1+Bb2:16 Bb1+Bb2:16 E2:d8 Bb1:16 Db2:16 Eb2:16 Eb2:16 "
        "Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Bb1+Bb2:8 Bb1+Bb2:16 Bb1+Bb2:16 E2:d8 Bb1:16 Db2:16 "
        "Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Bb1+Bb2:8 Bb1+Bb2:16 Bb1+Bb2:16 E2:d8 "
        "Bb1:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16"),   # 8 bar(s), 92 events
    "RIFF_C": ln(
        "Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2:16 D2:16 Db2:16 Bb1+Bb2:4 "
        "Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2:16 D2:16 Db2:16 Bb1+Bb2:4 Bb1+Ab2:32 "
        "Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2+Ab2:16 D2+A2:16 Db2+Ab2:16 Eb2+Bb2:d8 Eb2+Bb2:16 "
        "Eb2+Bb2:16 Eb2+Bb2:16 E2+B2:d8 E2+B2:16 E2+B2:16 E2+B2:16 Db2+Ab2:16 Db2+Ab2:16 Db2+Ab2:8"),   # 4 bar(s), 38 events
    "RIFF_D": ln("Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2+Ab2:16 D2+A2:16 Db2+Ab2:16"),   # 1 bar(s), 9 events
    "RIFF_E": ln(
        "Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2:16 D2:16 Db2:16 Bb1+Bb2:4 "
        "Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2:16 D2:16 Db2:16"),   # 2 bar(s), 18 events
    "RIFF_F": ln(
        "Eb2+Bb2:d8 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 E2+B2:d8 E2+B2:16 E2+B2:16 E2+B2:16 Db2+Ab2:16 "
        "Db2+Ab2:16 Db2+Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 Eb2+Bb2:16 "
        "Eb2+Bb2:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 "
        "Gb2+Db3:16 F2+C3:16 Db2:8 Db3:8 Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:16 "
        "Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 "
        "F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Db2:8 Db3:8 Ab2:8 "
        "Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16 Gb2+Db3:16 "
        "F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 "
        "Db2:8 Db3:8 Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16 "
        "Eb2+Bb2:16 Eb2+Bb2:16"),   # 8 bar(s), 85 events
    "RIFF_G": ln(
        "Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 "
        "F2+C3:16 Db2:8 Db3:8 Ab2:8"),   # 1 bar(s), 13 events
    "RIFF_H": ln(
        "Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:4 Bb1+Ab2:32 Bb1+Bb2:d8 Bb1:16 Db2:16 D2:16 Db2:16 Eb2+Bb2:d8 "
        "Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 E2+B2:d8 E2+B2:16 E2+B2:16 E2+B2:16 Db2+Ab2:16 Db2+Ab2:16 "
        "Db2+Ab2:8"),   # 2 bar(s), 20 events
    "RIFF_I": ln(
        "Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16 Gb2+Db3:16 "
        "F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 "
        "Db2:8 Db3:8 Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 "
        "Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 "
        "Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Db2:8 Db3:8 Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 "
        "Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 "
        "Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Db2:8 Db3:8 Ab2:8 Bb2+F3:4 "
        "Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 Eb2+Bb2:16 "
        "Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 "
        "F2+C3:16 Db2:8 Db3:8 Ab2:8"),   # 8 bar(s), 87 events
    "RIFF_J": ln("Bb2:4 Bb2:8 Bb2:16 Bb2:8 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 Eb2+Bb2:16 Eb2+Bb2:16"),   # 1 bar(s), 9 events
    "RIFF_K": ln(
        "Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 F2+C3:16 Gb2+Db3:16 "
        "F2+C3:16 Db2:8 Db3:8 Ab2:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:16 Eb2+Bb2:16 Eb2+Bb2:8 Eb2+Bb2:8 "
        "Eb2+Bb2:16 Eb2+Bb2:16"),   # 2 bar(s), 21 events
    "REST": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST3": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
}

RHYTHM_SCORE = [
    ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1), ("RIFF_D", 1), ("RIFF_E", 1), ("RIFF_F", 1),
    ("RIFF_G", 1), ("RIFF_B", 1), ("RIFF_E", 1), ("RIFF_H", 1), ("RIFF_C", 1), ("RIFF_I", 1),
    ("RIFF_J", 1), ("RIFF_K", 1), ("RIFF_G", 1), ("REST", 5), ("REST2", 1), ("REST3", 1),
    ("REST4", 1),
]

# ===================== BASS blocks (electric-bass-pick) =====================
BASS = {
    "REST": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "RIFF_A": ln(
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8 Ab1:16 "
        "Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8 Ab1:16 Bb1:16 "
        "Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8 Ab1:16 Bb1:16 Bb1:16 "
        "Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:8 Db1:16 Eb1:16 Eb1:8 Ab1:16 Bb1:16 Bb1:16 Bb0:16 "
        "E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 "
        "Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 Bb1:16 "
        "Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 "
        "Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 "
        "Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 "
        "Bb0:16 Db1:16 D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 "
        "Eb1:d8 Eb1:16 Eb1:16 Eb1:16 E1:d8 E1:16 E1:16 E1:16 Db1:16 Db1:16 Db1:8 Bb1:4 Ab1:32 Bb1:4 "
        "Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 "
        "D1:16 Db1:16 Bb1:4 Ab1:32 Bb1:4 Ab1:32 Bb1:d8 Bb0:16 Db1:16 D1:16 Db1:16 Eb1:d8 Eb1:16 "
        "Eb1:16 Eb1:16 E1:d8 E1:16 E1:16 E1:16 Db1:16 Db1:16 Db1:8"),   # 16 bar(s), 180 events
    "RIFF_B": ln(
        "Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 "
        "Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8 Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 "
        "Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8 "
        "Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 "
        "Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8 Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 "
        "Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8"),   # 8 bar(s), 84 events
    "RIFF_C": ln(
        "Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 "
        "Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8 Bb1:4 Bb1:d8 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 "
        "Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8"),   # 4 bar(s), 42 events
    "RIFF_D": ln(
        "Bb1:4 Bb1:8 Bb1:16 Bb1:8 Eb1:16 Eb1:8 Eb1:8 Eb1:16 Eb1:16 Gb1:16 F1:16 Gb1:16 F1:16 Gb1:16 "
        "F1:16 Gb1:16 F1:16 Gb1:16 F1:16 Db1:8 Db2:8 Ab1:8"),   # 2 bar(s), 22 events
    "RIFF_E": ln(
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 "
        "Bb1:8 Bb1:16 Bb1:16 Bb1:8 Bb1:16 Bb1:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16 E2:16"),   # 8 bar(s), 112 events
    "PEDAL": ln("Ab1:8 Ab1:16 Ab1:16 Ab1:8 Ab1:16 Ab1:8 Ab1:16 Ab1:8 Ab1:16 Ab1:16 Ab1:16 Ab1:16"),   # 1 bar(s), 12 events
    "RIFF_F": ln("Ab1:8 Ab1:16 Ab1:16 Ab1:8 Ab1:16 Ab1:8 B1:16 B1:16 B1:16 Gb2:16 B1:16 Gb2:16 B1:16"),   # 1 bar(s), 13 events
    "RIFF_G": ln("Bb0+Bb1:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST3": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "RIFF_H": ln(
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 "
        "Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 "
        "Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 "
        "Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 "
        "Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 "
        "Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 "
        "Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 "
        "Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 "
        "Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 "
        "Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 "
        "E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 "
        "Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 "
        "Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Ab1:16 "
        "Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 "
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 Eb1:16 "
        "Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 "
        "Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 "
        "Eb1:16 Eb1:16 Eb1:16"),   # 16 bar(s), 224 events
    "RIFF_I": ln(
        "Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 Eb2:16 Eb2:16 "
        "Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 Db1:16 Eb1:16 "
        "Eb1:16 Eb1:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E2:d8 Bb0:16 Db2:16 Eb2:16 Eb2:16 Eb2:16 Db2:16 "
        "Eb2:16 Eb2:16 Eb2:16 Ab1:16 Bb1:16 Bb1:16 Bb0:16 E1:d8 Bb0:16 Db1:16 Eb1:16 Eb1:16 Eb1:16 "
        "Db1:16 Eb1:16 Eb1:16 Eb1:16"),   # 4 bar(s), 56 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
}

BASS_SCORE = [
    ("REST", 1), ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1),
    ("RIFF_D", 2), ("RIFF_E", 3), ("PEDAL", 1), ("RIFF_F", 1), ("RIFF_G", 1), ("REST2", 1),
    ("REST3", 1), ("RIFF_H", 2), ("RIFF_I", 1), ("RIFF_G", 1), ("REST4", 1),
]

# ===================== DRUMS blocks (drum-kit) =====================
DRUMS = {
    "REST": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "GROOVE_A": ln(
        "kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 "
        "kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 "
        "kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 kick+tom-floor:16 "
        "kick+tom-floor:16"),   # 1 bar(s), 16 events
    "GROOVE_B": ln(
        "35+crash+crash2:8 35+crash:8 40+hihat-open:8 hihat-open:8 35+hihat-open:8 35+hihat-open:8 "
        "40+hihat-open:16 40:16 hihat-open:16 snare:16"),   # 1 bar(s), 10 events
    "GROOVE_C": ln(
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:16 40:32 40:16 40:32 "
        "35+40:16 35:16 35+kick+tom-floor:16 35+kick+tom-floor:16 35+kick+tom-floor:16"),   # 1 bar(s), 14 events
    "GROOVE_D": ln(
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:8 35+crash:16 35:16 "
        "40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32"),   # 1 bar(s), 14 events
    "GROOVE_E": ln(
        "35+crash+crash2:8 35+crash:8 40+hihat-open:8 hihat-open:8 35+hihat-open:8 35+hihat-open:8 "
        "40+hihat-open:16 40:16 hihat-open:16 40:16"),   # 1 bar(s), 10 events
    "GROOVE_F": ln(
        "35+crash:16 35+40:16 35:16 35:16 snare+crash:8 hihat-open:8 35+hihat-open:8 35+hihat-open:16 "
        "35:16 40:32 35+40:16 35:16 35:16 35:32"),   # 1 bar(s), 14 events
    "GROOVE_G": ln(
        "35+crash:16 35+40:16 35+40:16 35:16 40+crash:8 hihat-open:8 35+hihat-open:16 35:16 "
        "35+hihat-open:8 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32"),   # 1 bar(s), 15 events
    "GROOVE_H": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:8 35+crash:16 35:16 "
        "40+hihat-open:16 40:16 hihat-open:8"),   # 1 bar(s), 11 events
    "GROOVE_I": ln(
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32 "
        "35+crash:8 35+crash:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32 "
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32 "
        "35+crash:8 35+crash:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32"),   # 2 bar(s), 36 events
    "GROOVE_J": ln(
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32 "
        "35+crash:8 35+crash:16 35:16 35+kick+tom-floor:16 35+kick+tom-floor:16 35+kick+tom-floor:16 "
        "35+kick+tom-floor:16"),   # 1 bar(s), 16 events
    "GROOVE_K": ln(
        "35+crash:8 35+crash2:16 35:16 40+hihat-open:16 40:16 hihat-open:32 40:32 40:32 40:32 "
        "35+crash:8 35+crash:16 35:16 40+hihat-open:16 40:16 hihat-open:16 40:32 40:32"),   # 1 bar(s), 17 events
    "GROOVE_L": ln(
        "35+crash+crash2:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:16 40:16 35+hihat-open:16 "
        "35+40:16 35+40:16 35:16 tom-low:32 kick+tom-low:16 35:16 kick:32 kick+tom-floor:16"),   # 1 bar(s), 15 events
    "GROOVE_M": ln(
        "kick+crash:8 kick+crash:16 kick:16 40+hihat-open:16 40:16 hihat-open:16 40:16 35+crash:16 "
        "35:16 35:16 35:16 35+40+crash:16 35+40:16 35+china:16 35+40:16"),   # 1 bar(s), 15 events
    "GROOVE_N": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:16 40:16 35+crash:16 35+40:16 "
        "35+40:16 35:16 kick+tom-low:32 tom-low:32 kick:16 kick+tom-low:32 tom-low:32 35:16"),   # 1 bar(s), 16 events
    "GROOVE_O": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:16 40:16 35+crash:16 35+40:16 "
        "35+40:16 35:16 kick+tom-low:32 tom-low:32 kick:16 kick+tom-floor:32 tom-floor:32 35:16"),   # 1 bar(s), 16 events
    "GROOVE_P": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:16 40:16 35+crash:16 35+snare:16 "
        "35+snare+40:16 35:16 kick+tom-low:32 tom-low:32 kick:16 kick+tom-floor:32 tom-floor:32 35:16"),   # 1 bar(s), 16 events
    "GROOVE_Q": ln(
        "35+crash+crash2:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:16 35+40:16 "
        "35+40:32 40:16 35:16 35+40:32 40:32 35:32 35+40:32 40:32 35:16"),   # 1 bar(s), 16 events
    "GROOVE_R": ln(
        "35+crash+crash2:8 35+crash:8 40+hihat-open:8 hihat-open:8 35+hihat-open:16 35+40:16 35+40:16 "
        "35:16 kick+40+crash:32 40:32 kick:16 kick+40+crash:32 40:32 35:16"),   # 1 bar(s), 14 events
    "GROOVE_S": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:16 40:16 35+crash:8 35+crash:16 "
        "35:16 40+hihat-open:16 40:16 hihat-open:16 40:16"),   # 1 bar(s), 13 events
    "GROOVE_T": ln(
        "35+crash:16 35+40:16 35+40:16 35:16 35+40+crash:8 hihat-open:8 35+hihat-open:16 35:16 "
        "35+hihat-open:16 35:16 kick+40:32 40:32 kick:16 kick+tom-floor:32 tom-floor:32 35:16"),   # 1 bar(s), 16 events
    "GROOVE_U": ln(
        "35+crash:16 35+40:16 35+hihat-open:16 35:16 40+crash:8 hihat-open:8 35+hihat-open:16 35:16 "
        "35+hihat-open:16 35:16 40+hihat-open:16 40:16 hihat-open:16 40:16"),   # 1 bar(s), 14 events
    "GROOVE_V": ln(
        "35+crash+crash2:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:8 35+crash2:16 "
        "35:16 40:32 35+40:16 35:16 35+tom-low:32 tom-low:32 35:32"),   # 1 bar(s), 14 events
    "GROOVE_W": ln(
        "35+crash:8 35+crash:16 35:16 40+hihat-open:8 hihat-open:8 35+crash:16 35+tom-floor:16 "
        "35+tom-floor:16 35:16 35+tom-low:32 tom-low:32 35:16 35+tom-floor:32 tom-floor:32 35:16"),   # 1 bar(s), 15 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST3": ln("R:1"),   # 1 bar(s), 1 events
}

DRUMS_SCORE = [
    ("REST", 1), ("GROOVE_A", 2), ("GROOVE_B", 1), ("GROOVE_C", 1), ("GROOVE_D", 1), ("GROOVE_B", 1),
    ("GROOVE_E", 1), ("GROOVE_F", 1), ("GROOVE_E", 1), ("GROOVE_G", 1), ("GROOVE_H", 1), ("GROOVE_I", 1),
    ("GROOVE_J", 1), ("GROOVE_K", 1), ("GROOVE_I", 1), ("GROOVE_J", 1), ("GROOVE_L", 1), ("GROOVE_M", 1),
    ("GROOVE_N", 1), ("GROOVE_O", 1), ("GROOVE_P", 1), ("GROOVE_O", 1), ("GROOVE_Q", 2), ("GROOVE_E", 1),
    ("GROOVE_R", 1), ("GROOVE_S", 1), ("GROOVE_T", 1), ("GROOVE_U", 2), ("GROOVE_V", 1), ("GROOVE_W", 1),
    ("REST2", 7), ("REST3", 1),
]


# =========================== arrangement / plumbing ===========================
LANES = ('lead', 'rhythm', 'bass', 'drums')
INSTRUMENTS = {
    "lead": "distortion-guitar",
    "rhythm": "distortion-guitar",
    "bass": "electric-bass-pick",
    "drums": "drum-kit",
}
BLOCKS = {
    "lead": LEAD,
    "rhythm": RHYTHM,
    "bass": BASS,
    "drums": DRUMS,
}
SONG_MAPS = {
    "lead": LEAD_SCORE,
    "rhythm": RHYTHM_SCORE,
    "bass": BASS_SCORE,
    "drums": DRUMS_SCORE,
}

TEMPO_MAP = [
    {"beat": 0, "bpm": 55},
    {"beat": 20, "bpm": 57},
    {"beat": 36, "bpm": 56},
    {"beat": 44, "bpm": 55},
    {"beat": 52, "bpm": 56},
    {"beat": 56, "bpm": 57},
    {"beat": 60, "bpm": 58},
    {"beat": 64, "bpm": 59},
    {"beat": 68, "bpm": 60},
    {"beat": 84, "bpm": 59},
    {"beat": 164, "bpm": 60},
    {"beat": 396, "bpm": 48},
]

# Rebuild every lane from its song map; all lanes span the same bars, so they share
# one total length (asserted below) -- no manual rest-padding needed.
timeline = {lane: expand(BLOCKS[lane], SONG_MAPS[lane]) for lane in LANES}

composition = {
    "title": "Electric Wizard - Dopethrone (Recreation)",
    "bpm": 55,
    "time_signature": "4/4",
    "tempo_map": TEMPO_MAP,
    "tracks": [
        {"instrument": INSTRUMENTS[lane], "notes": timeline[lane]} for lane in LANES
    ],
}


if __name__ == "__main__":
    total = beats(timeline[LANES[0]])
    for lane in LANES:
        assert abs(beats(timeline[lane]) - total) < 1e-6, \
            f"{lane} misaligned ({beats(timeline[lane])} vs {total})"
    print(f"Title : Electric Wizard - Dopethrone (Recreation)")
    print(f"Lanes : {', '.join(LANES)}")
    print(f"Length: {total:.0f} beats")
    print("Blocks: " + ", ".join(f"{l}={len(BLOCKS[l])}" for l in LANES))
    nev = sum(len(t["notes"]) for t in composition["tracks"])
    print(f"Events: {nev} notes/chords across {len(composition['tracks'])} tracks")
    path = generate_midi_from_dict(composition)
    print(f"MIDI written: {path}")
    stem = Path(path).stem
    print(f'Render to WAV:  python render_wav.py 0.7 "{stem}"')
