#!/usr/bin/env python3
"""
Monolord - Audhumbla (Recreation)
=== a FAITHFUL recreation of a real doom song, written in the compose_doom_*.py idiom ===

Auto-generated by transcribe_song.py / analysis.extract_blocks from the Guitar Pro tab,
then iterable like compose_doom_drowned_cathedral.py. Each lane is expressed as named,
reusable BLOCKS (riffs / grooves / pedals / rests) plus a flat SONG MAP -- a
`[(block, count), ...]` score that cycles those blocks to rebuild the whole part. Tweak
a block, or re-order / re-count a song map, to spin a new piece off this structure.

  Key/feel : B Phrygian, 115 BPM, 182 bars / 662 beats
  Lanes    : lead=distortion-guitar, rhythm=distortion-guitar, bass=electric-bass-pick, drums=drum-kit

FAITHFUL on pitch, voicing, rhythm, every drum hit, the tempo map and the arrangement.
NOT reproduced: per-note velocity (absent from the source IR -> flat) and notated meter
changes (kept as a global 4/4 -- audio is unaffected since durations are absolute beats).
"""

import sys
from pathlib import Path

REPO = Path(__file__).parent
sys.path.insert(0, str(REPO))

from skills.generate_midi import generate_midi_from_dict, parse_duration


def ln(s):
    """Compact "P:dur P:dur ..." note string -> [('pitch', 'duration'), ...].

    `P` is a pitch (`B1`), a chord (`B2+Gb3+B3`), a drum name, or a rest (`R`);
    `dur` is a skill duration token (`2`, `d4`, `T8`). Whitespace-separated, so a
    block that took dozens of dict lines is one readable string here.
    """
    return [dict(zip(("pitch", "duration"), t.rsplit(":", 1))) for t in s.split()]


def expand(blocks, score):
    """A lane's [(block_name, count), ...] song map -> a flat list of note dicts."""
    out = []
    for name, count in score:
        out += blocks[name] * count
    return out


def beats(notes):
    return sum(parse_duration(n["duration"]) for n in notes)


# ===================== LEAD blocks (distortion-guitar) =====================
LEAD = {
    "RIFF_A": ln("B1+Gb2:4 B1+Gb2:d2"),   # 1 bar(s), 2 events
    "RIFF_B": ln("B2:2 B1:4 A2:4 R:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4"),   # 2 bar(s), 11 events
    "RIFF_C": ln("B1+Gb2:4 C2+G2:d2"),   # 1 bar(s), 2 events
    "REST": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "RIFF_D": ln("A2:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4"),   # 1 bar(s), 8 events
    "RIFF_E": ln("B1+Gb2:4 C2+G2:d2 C3:2 B1:4 C2+G2:4"),   # 2 bar(s), 5 events
    "RIFF_F": ln("R:4 C2:8 B1:8 C2:8 D2:8 D2:8 D2:8"),   # 1 bar(s), 7 events
    "RIFF_G": ln("B1+Gb2:4 B1+Gb2:d2 A2:16 B2:4 B2:8 B2:16 B1:4 A2:4"),   # 2 bar(s), 8 events
    "RIFF_H": ln("R:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4 B1+Gb2:4 C2+G2:d2"),   # 2 bar(s), 10 events
    "RIFF_I": ln("C3:2 B1:4 C2+G2:4"),   # 1 bar(s), 3 events
    "RIFF_J": ln("R:4 C2+G2:8 B1:8 C2:8 D2:8 D2:8 D2:8"),   # 1 bar(s), 7 events
    "RIFF_K": ln("B1+Gb2:4 B1+Gb2:2 B1:4"),   # 1 bar(s), 3 events
    "RIFF_L": ln("B1+Gb2:4 C2+G2:2 C2:4"),   # 1 bar(s), 3 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "RIFF_M": ln("B1+Gb2:4 B1+Gb2:2 B1+Gb2:4"),   # 1 bar(s), 3 events
    "RIFF_N": ln("B1+Gb2:4 C2+G2:2 C2+G2:4"),   # 1 bar(s), 3 events
    "PEDAL": ln("C3:2"),   # 1 bar(s), 1 events
    "REST3": ln("R:1 R:2 R:1 R:2 R:1 R:2 R:1 R:2"),   # 8 bar(s), 8 events
    "REST4": ln("R:1 R:d2 R:1 R:1"),   # 4 bar(s), 4 events
    "REST5": ln("R:1 R:1 R:4"),   # 2 bar(s), 3 events
    "REST6": ln("R:d2 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST7": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST8": ln("R:1 R:2"),   # 2 bar(s), 2 events
    "REST9": ln("R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2 R:d2"),   # 16 bar(s), 16 events
    "REST10": ln("R:1 R:d2 R:1 R:d2"),   # 4 bar(s), 4 events
    "REST11": ln("R:1 R:d2"),   # 2 bar(s), 2 events
    "RIFF_O": ln("C2+G2:4 C2:16 B1:16 C2:16 D2:16 D2:16 D2:16 B1+Gb2:8 B1+Gb2:4"),   # 1 bar(s), 9 events
    "REST12": ln("R:4 R:2"),   # 1 bar(s), 2 events
    "RIFF_P": ln("R:2 R:8 B1+Gb2:8"),   # 1 bar(s), 3 events
    "RIFF_Q": ln("B1+Gb2:8 C2+G2:d4 B5:2"),   # 1 bar(s), 3 events
    "RIFF_R": ln("R:4 A5:4 B5:4"),   # 1 bar(s), 3 events
    "RIFF_S": ln("B1+Gb2:4 B5:d2"),   # 1 bar(s), 2 events
    "REST13": ln("R:d2 R:1"),   # 2 bar(s), 2 events
    "REST14": ln("R:d2 R:d2"),   # 2 bar(s), 2 events
    "REST15": ln("R:1"),   # 1 bar(s), 1 events
    "RIFF_T": ln("B1+Gb2:d2"),   # 1 bar(s), 1 events
    "PEDAL2": ln("B3:d2"),   # 1 bar(s), 1 events
}

LEAD_SCORE = [
    ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1), ("REST", 1), ("RIFF_D", 1), ("RIFF_E", 1),
    ("RIFF_F", 1), ("RIFF_G", 1), ("RIFF_H", 1), ("RIFF_I", 1), ("RIFF_J", 1), ("RIFF_G", 1),
    ("REST", 1), ("RIFF_K", 1), ("RIFF_B", 1), ("RIFF_L", 1), ("REST2", 1), ("RIFF_M", 1),
    ("RIFF_B", 1), ("RIFF_N", 1), ("PEDAL", 1), ("REST3", 2), ("REST4", 1), ("REST5", 1),
    ("REST4", 1), ("REST6", 1), ("REST", 1), ("REST5", 1), ("REST7", 2), ("REST8", 1),
    ("REST7", 1), ("REST9", 2), ("REST10", 1), ("REST11", 1), ("RIFF_O", 1), ("REST12", 1),
    ("RIFF_P", 1), ("RIFF_Q", 1), ("RIFF_R", 1), ("RIFF_S", 1), ("REST13", 1), ("REST14", 1),
    ("REST15", 1), ("RIFF_T", 1), ("REST10", 1), ("PEDAL2", 1),
]

# ===================== RHYTHM blocks (distortion-guitar) =====================
RHYTHM = {
    "RIFF_A": ln("B1+Gb2:4 B1+Gb2:d2 R:1 R:1 B1+Gb2:4 C2+G2:d2"),   # 4 bar(s), 6 events
    "RIFF_B": ln("C3:2 B1:4 C2+G2:4 R:4 C2:8 B1:8 C2:8 D2:8 D2:8 D2:8"),   # 2 bar(s), 10 events
    "RIFF_C": ln("B1+Gb2:4 B1+Gb2:d2"),   # 1 bar(s), 2 events
    "RIFF_D": ln("B2:2 B1:4 A2:4"),   # 1 bar(s), 3 events
    "RIFF_E": ln("R:1 B1+Gb2:4 C2+G2:d2 C3:2 B1:4 C2+G2:4 R:4 C2:8 B1:8 C2:8 D2:8 D2:8 D2:8"),   # 4 bar(s), 13 events
    "RIFF_F": ln("C3:2 B1:4 C2+G2:4"),   # 1 bar(s), 3 events
    "RIFF_G": ln("R:4 C2+G2:8 B1:8 C2:8 D2:8 D2:8 D2:8"),   # 1 bar(s), 7 events
    "RIFF_H": ln("A2:16 B2:4 B2:8 B2:16 B1:4 A2:4"),   # 1 bar(s), 6 events
    "RIFF_I": ln("R:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4"),   # 1 bar(s), 8 events
    "RIFF_J": ln("B1+Gb2:4 C2+G2:d2"),   # 1 bar(s), 2 events
    "RIFF_K": ln("C3:2 B1+Gb2:4 C2+G2:4"),   # 1 bar(s), 3 events
    "RIFF_L": ln("R:4 C2+G2:8 B1+Gb2:8 C3+C4:8 D3+D4:8 D3+D4:8 D3+D4:8"),   # 1 bar(s), 7 events
    "RIFF_M": ln(
        "B1+Gb2:4 B1+Gb2:2 B1:4 B2:2 B1:4 A2:4 R:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4 "
        "B1+Gb2:4 C2+G2:2 C2:4"),   # 4 bar(s), 17 events
    "RIFF_N": ln("B1+Gb2:4 B1+Gb2:2 B1+Gb2:4"),   # 1 bar(s), 3 events
    "RIFF_O": ln("B2:2 B1:4 A2:4 R:4 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4"),   # 2 bar(s), 11 events
    "RIFF_P": ln("B1+Gb2:4 C2+G2:2 C2+G2:4 C3:2"),   # 2 bar(s), 4 events
    "RIFF_Q": ln("B1:4 C2+G2:2 C2:8 B1:8"),   # 1 bar(s), 4 events
    "RIFF_R": ln("C2:8 D2:8 D2:8 D2:8"),   # 1 bar(s), 4 events
    "RIFF_S": ln(
        "B1+Gb2:4 B1+Gb2:2 B1+Gb2:4 A2:16 B2:4 B2:8 B2:16 B1:4 A2:2 B1:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 "
        "F2:T4 D2:T4"),   # 4 bar(s), 16 events
    "RIFF_T": ln("B1+Gb2:4 C2+G2:2 C2:4"),   # 1 bar(s), 3 events
    "RIFF_U": ln("C3:2 B1+Gb2:4 C2+G2:2 C2+G2:8 B1+Gb2:8"),   # 2 bar(s), 5 events
    "RIFF_V": ln("C2+G2:8 D2+A2:8 D2+A2:8 D2+A2:8"),   # 1 bar(s), 4 events
    "RIFF_W": ln("B1+Gb2:4 C2+G2:2 C2+G2:8 B1+Gb2:8 C2+G2:8 D2+A2:8 D2+A2:8 D2+A2:8 D2+A2:8 D2+A2:8"),   # 2 bar(s), 10 events
    "RIFF_X": ln("B1+Gb2:2 B1+Gb2:4 A2:16 B2:d8"),   # 1 bar(s), 4 events
    "RIFF_Y": ln("R:4 B1+Gb2:4 A2:2"),   # 1 bar(s), 3 events
    "RIFF_Z": ln("B1+Gb2:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4 B1+Gb2:4"),   # 1 bar(s), 8 events
    "RIFF_AA": ln("C2+G2:2 C2+G2:4 C3:2"),   # 1 bar(s), 3 events
    "RIFF_AB": ln("B1+Gb2:2 B1+Gb2:4 B2:4"),   # 1 bar(s), 3 events
    "RIFF_AC": ln("B1+Gb2:4 Eb2:T4 Gb2:T4 Eb2:T4 D2:T4 F2:T4 D2:T4"),   # 1 bar(s), 7 events
    "RIFF_AD": ln("B1+Gb2:4 C2+G2:2 C2+G2:4"),   # 1 bar(s), 3 events
    "RIFF_AE": ln("R:4 C2+G2:8 B1+Gb2:8 C2+G2:8 D2+A2:8 D2+A2:8 D2+A2:8"),   # 1 bar(s), 7 events
    "RIFF_AF": ln("D2+A2:8 D2+A2:8 B1+Gb2:2 B1+Gb2:4"),   # 1 bar(s), 4 events
    "RIFF_AG": ln("B1:4 C2+G2:2 C2:4"),   # 1 bar(s), 3 events
    "RIFF_AH": ln("C2+G2+C3:2 C2+G2+C3:8 D2+A2+D3:8 D2+A2+D3:8 D2+A2+D3:8 D2+A2+D3:4"),   # 1 bar(s), 6 events
    "RIFF_AI": ln("B1+Gb2+B2:4 B1+Gb2+B2:4 B1+Gb2+B2:4 B1+Gb2+B2:4"),   # 1 bar(s), 4 events
    "RIFF_AJ": ln("E2+A2:8 Gb2+B2:8 Gb2+B2:8 G2+C3:8 G2+C3:8 Gb2+B2:8 E2+A2:8 Gb2+B2:8"),   # 1 bar(s), 8 events
    "RIFF_AK": ln("F2+Bb2:4 F2+Bb2:4 F2+Bb2:4 F2+Bb2:8 Bb2+Eb3:8"),   # 1 bar(s), 5 events
    "RIFF_AL": ln("Eb3+Bb3:8 D3+A3:8 D3+A3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 A2+E3:8 C3+G3:8"),   # 1 bar(s), 8 events
    "RIFF_AM": ln("B2+Gb3:4 B2+Gb3:4 B2+Gb3:4 B2+Gb3:4"),   # 1 bar(s), 4 events
    "RIFF_AN": ln(
        "A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 A2+E3:8 B2+Gb3:8 Bb2+F3:4 Bb2+F3:4 "
        "Bb2+F3:4 Bb2+F3:4"),   # 2 bar(s), 12 events
    "RIFF_AO": ln("F2+A2:2 E2+Ab2:2"),   # 1 bar(s), 2 events
    "RIFF_AP": ln("B1+Gb2:4 B1+Gb2:4 B1+Gb2:4 B1+Gb2:4"),   # 1 bar(s), 4 events
    "RIFF_AQ": ln(
        "A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 A2+E3:8 B2+Gb3:8 Bb2+F3:4 Bb2+F3:4 "
        "Bb2+F3:4 Bb2+F3:8 Eb3+Bb3:8 Eb3+Bb3:8 D3+A3:8 D3+A3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 A2+E3:8 "
        "C3+G3:8 B2+Gb3:4 B1+Gb2:4 B2+Gb3:4 B2+Gb3:4"),   # 4 bar(s), 25 events
    "RIFF_AR": ln("F2+A2:4 E2+Ab2:4 Eb2+G2:4 D2+Gb2:4"),   # 1 bar(s), 4 events
    "RIFF_AS": ln(
        "B1+Gb2:4 B2+Gb3:4 B2+Gb3:4 B2+Gb3:4 A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 "
        "A2+E3:8 B2+Gb3:8"),   # 2 bar(s), 12 events
    "RIFF_AT": ln("Bb2+F3:4 Bb2+F3:4 Bb2+F3:4 Bb2+F3:8 Eb3+Bb3:8"),   # 1 bar(s), 5 events
    "RIFF_AU": ln("Bb2+F3:8 A2+E3:8 A2+E3:8 G2+D3:8 G2+D3:8 Gb2+Db3:8 E2+B2:8 G2+D3:8"),   # 1 bar(s), 8 events
    "RIFF_AV": ln("Gb2+Db3:4 B1+Gb2:4 Gb2+Db3:4 Gb2+Db3:4"),   # 1 bar(s), 4 events
    "RIFF_AW": ln("E2+B2:8 Gb2+Db3:8 Gb2+Db3:8 G2+D3:8 G2+D3:8 Gb2+Db3:8 E2+B2:8 Gb2+Db3:8"),   # 1 bar(s), 8 events
    "RIFF_AX": ln("F2+C3:4 F2+C3:4 F2+C3:4 F2+C3:4"),   # 1 bar(s), 4 events
    "RIFF_AY": ln("Bb2:2 A2:2"),   # 1 bar(s), 2 events
    "RIFF_AZ": ln("Eb2+Bb2:8 D2+A2:8 D2+A2:8 C2+G2:8 C2+G2:8 B1+Gb2:8 B1+Gb2:8 C2+G2:8"),   # 1 bar(s), 8 events
    "RIFF_BA": ln("B1+E2:8 B1+Gb2:8 B1+Gb2:8 C2+G2:8 C2+G2:8 B1+Gb2:8 B1+E2:8 B1+Gb2:8"),   # 1 bar(s), 8 events
    "RIFF_BB": ln("B1+F2:4 B1+F2:4 B1+F2:4 B1+F2:4"),   # 1 bar(s), 4 events
    "RIFF_BC": ln("Bb2:4 Gb2:4 A2:4 F2:4"),   # 1 bar(s), 4 events
    "RIFF_BD": ln("B1+Gb2:4 Gb5+B5:4"),   # 1 bar(s), 2 events
    "RIFF_BE": ln(
        "B1+Gb2:4 B2+Gb3:4 B2+Gb3:4 B2+Gb3:4 A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 "
        "A2+E3:8 B2+Gb3:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:4 Bb2+F3:8 Eb3+Bb3:8 Eb3+Bb3:8 D3+A3:8 D3+A3:8 "
        "C3+G3:8 C3+G3:8 B2+Gb3:8 A2+E3:8 C3+G3:8"),   # 4 bar(s), 25 events
    "RIFF_BF": ln(
        "B2+Gb3:4 B1+Gb2:4 B2+Gb3:4 B2+Gb3:4 A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 "
        "A2+E3:8 B2+Gb3:8"),   # 2 bar(s), 12 events
    "RIFF_BG": ln("Bb2+F3:4 Bb2+F3:4 Bb2+F3:4 Bb2+F3:4"),   # 1 bar(s), 4 events
    "RIFF_BH": ln("A2:2 Ab2:2"),   # 1 bar(s), 2 events
    "RIFF_BI": ln(
        "B2+Gb3:4 B1+Gb2:4 B2+Gb3:4 B2+Gb3:4 A2+E3:8 B2+Gb3:8 B2+Gb3:8 C3+G3:8 C3+G3:8 B2+Gb3:8 "
        "A2+E3:8 B2+Gb3:8 Bb2+F3:4 Bb2+F3:4 Bb2+F3:4 Bb2+F3:4 F2+A2:4 E2+Ab2:4 Eb2+G2:4 D2+Gb2:4"),   # 4 bar(s), 20 events
    "REST": ln("R:d2"),   # 1 bar(s), 1 events
    "RIFF_BJ": ln("Bb2:4 B1+Gb2:8 Eb2+Bb2:8 D2+A2:8 B1+Gb2:8"),   # 1 bar(s), 5 events
    "RIFF_BK": ln("C2+G2:4 C2+G2:8 Gb2+Db3:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_BL": ln("C2+G2:4 C2+G2:8 C2+G2:16 D2+A2:16 D2+A2:16 D2+A2:16 D2+A2:16 D2+A2:16"),   # 1 bar(s), 8 events
    "RIFF_BM": ln("B1+Gb2:4 B1+Gb2:8 C3:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_BN": ln("A2:4 B1+Gb2:8 Eb2+Bb2:8 D2+A2:8 B1+Gb2:8"),   # 1 bar(s), 5 events
    "REST2": ln("R:d2 R:d2"),   # 2 bar(s), 2 events
    "RIFF_BO": ln("C2+G2:4 C2+G2:8 Db3+Ab3:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_BP": ln("B1+Gb2:4 B1+Gb2:8 B1+B2:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_BQ": ln("A2:4 B1:8 Eb2+Bb2:8 D2+A2:8 B1:8"),   # 1 bar(s), 5 events
    "RIFF_BR": ln("C2+G2:4 B1:8 C3:4 B1:8"),   # 1 bar(s), 4 events
    "PEDAL": ln("B2:d2"),   # 1 bar(s), 1 events
    "RIFF_BS": ln(
        "B1+Gb2:4 B1+Gb2:8 B2:4 B1+Gb2:8 A2:4 B1+Gb2:8 Eb2:T8 Gb2:T8 Eb2:T8 D2:T8 F2:T8 D2:T8 "
        "B1+Gb2:8"),   # 2 bar(s), 13 events
    "RIFF_BT": ln("C2+G2:4 C2+G2:8 F2+C3:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_BU": ln("C2+G2:4 C2+G2:16 C2+G2:16 C2+G2:16 D2+A2:16 D2+A2:16 D2+A2:16 D2+A2:16 D2+A2:16"),   # 1 bar(s), 9 events
    "RIFF_BV": ln("C2+G2:4 C2:8 C3:4 B1:8"),   # 1 bar(s), 4 events
    "RIFF_BW": ln("C2+G2:4 C2+G2:16 B1:16 C2:16 D2:16 D2:16 D2:16 D2:16 D2:16"),   # 1 bar(s), 9 events
    "RIFF_BX": ln("B1+Gb2:4 B1:8 B2:4 B1:8"),   # 1 bar(s), 4 events
    "RIFF_BY": ln("A2:4 B1:8 Eb2:T8 Gb2:T8 Eb2:T8 D2:T8 F2:T8 D2:T8 B1:8"),   # 1 bar(s), 9 events
    "RIFF_BZ": ln("C2+G2:4 C2:8 C3:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_CA": ln("C2+G2:4 C2+G2:16 C2+G2:16 C2:16 D2:16 D2:16 D2:16 D2:16 D2:16"),   # 1 bar(s), 9 events
    "RIFF_CB": ln("C2+G2:4 C2+G2:8 B2:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_CC": ln("B1+Gb2:4 B1+Gb2:8 A2:32 B2:4 B1+Gb2:8 A2:8 A2:16 A2:32"),   # 1 bar(s), 8 events
    "RIFF_CD": ln("B1:8 Eb2:T8 Gb2:T8 Eb2:T8 D2:T8 F2:T8 D2:T8 B1:8 C2+G2:4"),   # 1 bar(s), 9 events
    "RIFF_CE": ln("C2:8 C3:4 B1:8 C2+G2:4 C2+G2:16 C2+G2:16 C2+G2:16 C2+G2:16"),   # 1 bar(s), 8 events
    "RIFF_CF": ln("C2+G2:16 C2+G2:16 C2+G2:16 C2+G2:16 B1+Gb2:4 B1+Gb2:8 A2:32 B2:16 B2:32"),   # 1 bar(s), 9 events
    "RIFF_CG": ln("R:8 B1:8 A2:4 B1:8 Eb2:T8 Gb2:T8 Eb2:T8 D2:T8 F2:T8 D2:T8 B1:8"),   # 1 bar(s), 11 events
    "RIFF_CH": ln("C2+G2:4 C2:16 B1:16 C2:16 D2:16 D2:16 D2:16 B1+Gb2:8 B1+Gb2:4"),   # 1 bar(s), 9 events
    "REST3": ln("R:4 R:2"),   # 1 bar(s), 2 events
    "RIFF_CI": ln("R:2 R:8 B1+Gb2:8"),   # 1 bar(s), 3 events
    "RIFF_CJ": ln("B1+Gb2:8 C2+G2:d4 B5:2"),   # 1 bar(s), 3 events
    "RIFF_CK": ln("R:4 A5:4 B5:4"),   # 1 bar(s), 3 events
    "RIFF_CL": ln("B1+Gb2:4 R:d2"),   # 1 bar(s), 2 events
    "RIFF_CM": ln("R:4 B1+Gb2:8 C2+G2:d4"),   # 1 bar(s), 3 events
    "RIFF_CN": ln("B1+Gb2:8 B1+Gb2:2 B1+Gb2:4 B1+Gb2:8"),   # 1 bar(s), 4 events
    "RIFF_CO": ln("B1+Gb2+B2:d2"),   # 1 bar(s), 1 events
    "REST4": ln("R:1 R:d2"),   # 2 bar(s), 2 events
    "RIFF_CP": ln("B1+Gb2+B2:1"),   # 1 bar(s), 1 events
}

RHYTHM_SCORE = [
    ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1), ("RIFF_D", 1), ("RIFF_E", 1), ("RIFF_A", 1),
    ("RIFF_F", 1), ("RIFF_G", 1), ("RIFF_C", 1), ("RIFF_H", 1), ("RIFF_I", 1), ("RIFF_J", 1),
    ("RIFF_K", 1), ("RIFF_L", 1), ("RIFF_M", 1), ("RIFF_B", 1), ("RIFF_M", 1), ("RIFF_K", 1),
    ("RIFF_G", 1), ("RIFF_N", 1), ("RIFF_O", 1), ("RIFF_P", 1), ("RIFF_Q", 1), ("RIFF_R", 1),
    ("RIFF_S", 1), ("RIFF_T", 1), ("RIFF_U", 1), ("RIFF_V", 1), ("RIFF_S", 1), ("RIFF_P", 1),
    ("RIFF_W", 1), ("RIFF_X", 1), ("RIFF_Y", 1), ("RIFF_Z", 1), ("RIFF_AA", 1), ("RIFF_W", 1),
    ("RIFF_AB", 1), ("RIFF_Y", 1), ("RIFF_AC", 1), ("RIFF_AD", 1), ("RIFF_K", 1), ("RIFF_AE", 1),
    ("RIFF_AF", 1), ("RIFF_O", 1), ("RIFF_AG", 1), ("RIFF_F", 1), ("RIFF_AH", 1), ("RIFF_AI", 1),
    ("RIFF_AJ", 1), ("RIFF_AK", 1), ("RIFF_AL", 1), ("RIFF_AM", 1), ("RIFF_AN", 1), ("RIFF_AO", 1),
    ("RIFF_AP", 1), ("RIFF_AQ", 1), ("RIFF_AN", 1), ("RIFF_AR", 1), ("RIFF_AS", 1), ("RIFF_AT", 1),
    ("RIFF_AU", 1), ("RIFF_AV", 1), ("RIFF_AW", 1), ("RIFF_AX", 1), ("RIFF_AY", 1), ("RIFF_AS", 1),
    ("RIFF_AT", 1), ("RIFF_AZ", 1), ("RIFF_AP", 1), ("RIFF_BA", 1), ("RIFF_BB", 1), ("RIFF_AR", 1),
    ("RIFF_BC", 1), ("RIFF_BD", 1), ("RIFF_BE", 1), ("RIFF_BF", 1), ("RIFF_BG", 1), ("RIFF_BH", 1),
    ("RIFF_BE", 1), ("RIFF_BI", 1), ("REST", 1), ("RIFF_BJ", 1), ("RIFF_BK", 1), ("RIFF_BL", 1),
    ("RIFF_BM", 1), ("RIFF_BN", 1), ("RIFF_BK", 1), ("REST2", 1), ("REST", 1), ("RIFF_BO", 1),
    ("RIFF_BL", 1), ("RIFF_BP", 1), ("RIFF_BQ", 1), ("RIFF_BR", 1), ("PEDAL", 1), ("RIFF_BS", 1),
    ("RIFF_BT", 1), ("RIFF_BU", 1), ("RIFF_BS", 1), ("RIFF_BV", 1), ("RIFF_BW", 1), ("RIFF_BX", 1),
    ("RIFF_BY", 1), ("RIFF_BZ", 1), ("RIFF_CA", 1), ("RIFF_BS", 1), ("RIFF_CB", 1), ("RIFF_BW", 1),
    ("RIFF_CC", 1), ("RIFF_CD", 1), ("RIFF_CE", 1), ("RIFF_CF", 1), ("RIFF_CG", 1), ("RIFF_BV", 1),
    ("RIFF_CH", 1), ("REST3", 1), ("RIFF_CI", 1), ("RIFF_CJ", 1), ("RIFF_CK", 1), ("RIFF_CL", 1),
    ("RIFF_CM", 1), ("RIFF_CN", 1), ("REST", 1), ("RIFF_CO", 1), ("REST4", 2), ("RIFF_CP", 1),
    ("REST2", 1),
]

# ===================== BASS blocks (electric-bass-pick) =====================
BASS = {
    "RIFF_A": ln(
        "B0:4 B0:d2 R:1 R:1 B0:4 C1:d2 R:1 R:1 B0:4 B0:d2 R:1 R:1 B0:4 C1:d2 R:1 R:1 B0:4 B0:d2 R:1 "
        "R:1 B0:4 C1:d2"),   # 16 bar(s), 22 events
    "RIFF_B": ln(
        "R:1 R:1 B0:4 B0:d2 R:1 R:1 B0:4 C1:d2 R:1 R:1 B0:4 B0:d2 R:1 R:1 B0:4 C1:d2 R:1 R:1 B0:4 "
        "B0:d2 R:1"),   # 16 bar(s), 21 events
    "RIFF_C": ln("R:1 B0:4 C1:d2 R:1 R:1 B0:4 B0:d2 R:1 R:1 B0:4 C1:d2"),   # 8 bar(s), 11 events
    "REST": ln("R:2 R:1"),   # 2 bar(s), 2 events
    "REST2": ln("R:2"),   # 1 bar(s), 1 events
    "PEDAL": ln("B0:4 B0:d2"),   # 1 bar(s), 2 events
    "RIFF_D": ln("B0:4 C1:d2 R:2 R:1 R:2"),   # 4 bar(s), 5 events
    "PEDAL2": ln("B0:4 B0:2 B0:4"),   # 1 bar(s), 3 events
    "PEDAL3": ln("B1:2"),   # 1 bar(s), 1 events
    "RIFF_E": ln("B0:4 A1:2 B0:4"),   # 1 bar(s), 3 events
    "RIFF_F": ln("Eb1:4 D1:4"),   # 1 bar(s), 2 events
    "RIFF_G": ln("B0:4 C1:2 C1:4"),   # 1 bar(s), 3 events
    "PEDAL4": ln("C2:2"),   # 1 bar(s), 1 events
    "RIFF_H": ln("B0:4 C1:2 C1:4 C1:8 D1:8 D1:8 D1:8 D1:8 D1:8 B0:2 B0:4 B1:4 R:4 B0:4 A1:2"),   # 4 bar(s), 15 events
    "RIFF_I": ln("B0:4 Eb1:4 D1:4 B0:4"),   # 1 bar(s), 4 events
    "PEDAL5": ln("C1:2 C1:4 C2:2"),   # 1 bar(s), 3 events
    "RIFF_J": ln("B0:4 Eb1:4 D1:4"),   # 1 bar(s), 3 events
    "RIFF_K": ln("B0:4 C1:2 C1:4 C2:2 B0:4 C1:4"),   # 2 bar(s), 6 events
    "RIFF_L": ln("R:4 C1:4 C1:8 D1:d4"),   # 1 bar(s), 4 events
    "RIFF_M": ln("D1:4 B0:2 B0:4"),   # 1 bar(s), 3 events
    "RIFF_N": ln("B1:2 B0:4 A1:4"),   # 1 bar(s), 3 events
    "RIFF_O": ln("R:4 B0:4 Eb1:4 D1:4"),   # 1 bar(s), 4 events
    "RIFF_P": ln("C1:4 C1:4 C1:4 C1:8 D1:8 D1:8 D1:8"),   # 1 bar(s), 7 events
    "RIFF_Q": ln("B0:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST3": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
    "RIFF_R": ln("F1:2 E1:2"),   # 1 bar(s), 2 events
    "RIFF_S": ln("F1:4 E1:4 Eb1:4 D1:4"),   # 1 bar(s), 4 events
    "RIFF_T": ln("B0:4 B1:4 B1:4 B1:4 A1:8 B1:8 B1:8 C2:8 C2:8 B1:8 A1:8 B1:8"),   # 2 bar(s), 12 events
    "PEDAL6": ln("Bb1:4 Bb1:4 Bb1:4 Bb1:4"),   # 1 bar(s), 4 events
    "RIFF_U": ln("Eb1:8 D1:8 D1:8 C1:8 C1:8 B0:8 B0:8 C1:8"),   # 1 bar(s), 8 events
    "RIFF_V": ln("B0:4 B0:4 B0:4 B0:4 B0:8 B0:8 B0:8 C1:8 C1:8 B0:8 B0:8 B0:8"),   # 2 bar(s), 12 events
    "PEDAL7": ln("B0:4 B0:4 B0:4 B0:4"),   # 1 bar(s), 4 events
    "PEDAL8": ln("B0:8 B0:8 B0:8 B0:8 B0:8 B0:8 B0:8 B0:8"),   # 1 bar(s), 8 events
    "RIFF_W": ln("Eb1:8 D1:8 D1:8 C1:8 C1:8 B0:8 B0:4"),   # 1 bar(s), 7 events
    "RIFF_X": ln("Bb1:4 Bb1:4 Bb1:4 Bb1:4 F1:4 E1:4 Eb1:4 D1:4"),   # 2 bar(s), 8 events
    "REST5": ln("R:1 R:2"),   # 2 bar(s), 2 events
    "RIFF_Y": ln(
        "B0:4 B1:4 B1:4 B1:4 A1:8 B1:8 B1:8 C2:8 C2:8 B1:8 A1:8 B1:8 Bb1:4 Bb1:4 Bb1:4 Bb1:4 Eb2:8 "
        "D2:8 D2:8 C2:8 C2:8 B1:8 A1:8 C2:8"),   # 4 bar(s), 24 events
    "PEDAL9": ln("B1:4 B0:4 B1:4 B1:4"),   # 1 bar(s), 4 events
    "RIFF_Z": ln("A1:8 B1:8 B1:8 C2:8 C2:8 B1:8 A1:8 C2:8"),   # 1 bar(s), 8 events
    "RIFF_AA": ln("A1:8 B1:8 B1:8 C2:8 C2:8 B1:8 A1:8 B1:8 Bb1:4 Bb1:4 Bb1:4 Bb1:4"),   # 2 bar(s), 12 events
    "RIFF_AB": ln(
        "B0:4 B0:8 B1:4 B0:8 A1:4 B0:8 Eb1:8 D1:8 B0:8 C1:4 C1:8 C2:4 B0:8 C1:4 C1:8 C1:16 D1:16 "
        "D1:16 D1:16 D1:16 D1:16"),   # 4 bar(s), 21 events
    "RIFF_AC": ln("B0:4 B0:8 C2:4 B0:8"),   # 1 bar(s), 4 events
    "RIFF_AD": ln("A1:4 B0:8 Eb1:8 D1:8 B0:8"),   # 1 bar(s), 5 events
    "RIFF_AE": ln("C1:4 C1:8 Db2:4 B0:8"),   # 1 bar(s), 4 events
    "RIFF_AF": ln("C1:d4 C1:16 D1:16 D1:16 D1:16 D1:16 D1:16"),   # 1 bar(s), 7 events
    "PEDAL10": ln("B0:4 B0:8 B1:4 B0:8"),   # 1 bar(s), 4 events
    "RIFF_AG": ln("A1:4 B0:8 E1:d8 D1:d8"),   # 1 bar(s), 4 events
    "RIFF_AH": ln(
        "C1:4 C1:8 C2:4 B0:8 C1:4 C1:8 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 B0:4 B0:8 B1:4 B0:8 A1:4 "
        "B0:8 Eb1:8 D1:8 B0:8"),   # 4 bar(s), 21 events
    "RIFF_AI": ln("C1:4 C1:8 C2:4 B0:8 C1:4 C1:8 C1:16 D1:16 D1:16 D1:16 D1:16 D1:16"),   # 2 bar(s), 12 events
    "RIFF_AJ": ln("B0:4 B0:8 B1:4 B0:8 A1:4 B0:8 Eb1:8 D1:8 B0:8"),   # 2 bar(s), 9 events
    "RIFF_AK": ln("C1:4 C1:8 C2:4 B0:8"),   # 1 bar(s), 4 events
    "RIFF_AL": ln("C1:4 C1:8 C1:16 C1:16 C1:16 D1:16 D1:16 D1:16"),   # 1 bar(s), 8 events
    "RIFF_AM": ln(
        "B0:4 B0:8 B1:4 B0:8 A1:4 B0:8 Eb1:8 D1:8 B0:8 C1:4 C1:8 C2:d4 C1:4 C1:8 C1:16 D1:16 D1:16 "
        "D1:16 D1:16 D1:16"),   # 4 bar(s), 20 events
    "RIFF_AN": ln("B0:4 B0:8 B1:4 B0:8 A1:4"),   # 1 bar(s), 5 events
    "RIFF_AO": ln("B0:8 Eb1:8 D1:8 B0:8 C1:4"),   # 1 bar(s), 5 events
    "RIFF_AP": ln("C1:8 C2:4 B0:8 C1:4 C1:16 C1:16 C1:16 D1:16"),   # 1 bar(s), 8 events
    "RIFF_AQ": ln("R:8 D1:16 D1:16 B0:4 B0:8 B1:8"),   # 1 bar(s), 6 events
    "RIFF_AR": ln("B0:8 A1:4 B0:8 Eb1:8 D1:8 C1:8 B0:8"),   # 1 bar(s), 7 events
    "PEDAL11": ln("C1:4 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16 C1:16"),   # 1 bar(s), 13 events
    "PEDAL12": ln("B0:8 B0:8 R:2"),   # 1 bar(s), 3 events
    "REST6": ln("R:d2"),   # 1 bar(s), 1 events
    "RIFF_AS": ln("B0:8 C1:2 R:d4"),   # 1 bar(s), 3 events
    "PEDAL13": ln("B0:4 R:d2"),   # 1 bar(s), 2 events
    "RIFF_AT": ln("R:4 B0:8 C1:d4"),   # 1 bar(s), 3 events
    "PEDAL14": ln("B0:8 B0:2 B0:8"),   # 1 bar(s), 3 events
    "REST7": ln("R:d2 R:1"),   # 2 bar(s), 2 events
}

BASS_SCORE = [
    ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1), ("REST", 1), ("REST2", 1), ("PEDAL", 1),
    ("REST", 1), ("REST2", 1), ("RIFF_D", 1), ("PEDAL2", 1), ("PEDAL3", 1), ("RIFF_E", 1),
    ("RIFF_F", 1), ("RIFF_G", 1), ("PEDAL4", 1), ("RIFF_H", 1), ("RIFF_I", 1), ("PEDAL5", 1),
    ("RIFF_H", 1), ("RIFF_J", 1), ("RIFF_K", 1), ("RIFF_L", 1), ("RIFF_M", 1), ("RIFF_N", 1),
    ("RIFF_O", 1), ("RIFF_K", 1), ("RIFF_P", 1), ("RIFF_Q", 1), ("REST3", 1), ("REST4", 1),
    ("RIFF_R", 1), ("RIFF_Q", 1), ("REST3", 1), ("REST4", 1), ("RIFF_S", 1), ("RIFF_T", 1),
    ("PEDAL6", 1), ("RIFF_U", 1), ("RIFF_V", 1), ("PEDAL7", 1), ("RIFF_R", 1), ("PEDAL7", 1),
    ("PEDAL8", 1), ("PEDAL6", 1), ("RIFF_W", 1), ("RIFF_V", 1), ("RIFF_X", 1), ("REST5", 1),
    ("RIFF_Y", 1), ("PEDAL9", 1), ("RIFF_Z", 1), ("PEDAL6", 1), ("RIFF_R", 1), ("RIFF_Y", 1),
    ("PEDAL9", 1), ("RIFF_AA", 1), ("RIFF_S", 1), ("RIFF_AB", 1), ("RIFF_AC", 1), ("RIFF_AD", 1),
    ("RIFF_AE", 1), ("RIFF_AF", 1), ("PEDAL10", 1), ("RIFF_AG", 1), ("RIFF_AH", 2), ("RIFF_AI", 1),
    ("RIFF_AJ", 1), ("RIFF_AK", 1), ("RIFF_AL", 1), ("RIFF_AM", 2), ("RIFF_AN", 1), ("RIFF_AO", 1),
    ("RIFF_AP", 1), ("RIFF_AQ", 1), ("RIFF_AR", 1), ("RIFF_AK", 1), ("PEDAL11", 1), ("PEDAL12", 1),
    ("REST6", 1), ("RIFF_AS", 1), ("REST6", 1), ("PEDAL13", 1), ("RIFF_AT", 1), ("REST4", 1),
    ("PEDAL14", 1), ("REST7", 3), ("REST6", 2),
]

# ===================== DRUMS blocks (drum-kit) =====================
DRUMS = {
    "GROOVE_A": ln(
        "kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 "
        "kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 "
        "kick+crash:4 kick+crash:d2"),   # 16 bar(s), 22 events
    "GROOVE_B": ln(
        "R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 "
        "kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1"),   # 16 bar(s), 21 events
    "GROOVE_C": ln(
        "R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 kick+crash:d2 R:1 R:1 kick+crash:4 "
        "kick+crash:d2"),   # 8 bar(s), 11 events
    "GROOVE_D": ln("R:2 R:1 R:2 kick+crash:4 kick+crash:d2"),   # 4 bar(s), 5 events
    "REST": ln("R:2"),   # 1 bar(s), 1 events
    "GROOVE_E": ln(
        "tom-floor-low:8 tom-floor-low:8 tom-floor-low:8 tom-floor-low:8 tom-floor-low:8 "
        "tom-floor-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_F": ln("tom-floor-low:8 tom-floor-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 4 events
    "GROOVE_G": ln("kick+crash:4 kick+crash:4 hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_H": ln(
        "snare+hihat-open:4 hihat-open:4 kick+hihat-open:4 kick+hihat-open:4 hihat-open:4 "
        "kick+hihat-open:4"),   # 2 bar(s), 6 events
    "GROOVE_I": ln(
        "snare:8 kick:8 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8 "
        "tom-floor-low+tom-low:8"),   # 1 bar(s), 6 events
    "GROOVE_J": ln("kick+crash:4 hihat-open:4 kick+hihat-open:4 snare+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_K": ln("hihat-open:4 kick+hihat-open:4 kick+hihat-open:4 hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_L": ln("kick+hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:4"),   # 1 bar(s), 5 events
    "GROOVE_M": ln("kick+hihat-open:4 hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 5 events
    "GROOVE_N": ln("kick+hihat-open:4 kick+hihat-open:4 snare+hihat-open:8 kick:8 hihat-open:8 snare:8"),   # 1 bar(s), 6 events
    "GROOVE_O": ln("snare:8 tom-low:8 tom-low:8 tom-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 6 events
    "GROOVE_P": ln("kick+crash:4 hihat-open:4 kick+hihat-open:4 snare+crash:4"),   # 1 bar(s), 4 events
    "GROOVE_Q": ln("kick+hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 3 events
    "GROOVE_R": ln("kick+hihat-open:4 kick+hihat-open:4 hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_S": ln("snare+hihat-open:4 hihat-open:4 kick+hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_T": ln("hihat-open:4 kick+hihat-open:4 snare:8 kick:8 snare:8 tom-low:T8 tom-low:T8 tom-low:T8"),   # 1 bar(s), 8 events
    "GROOVE_U": ln("kick:4 kick+crash:4 hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_V": ln("hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 snare:8 snare:8"),   # 1 bar(s), 5 events
    "GROOVE_W": ln("snare:4 kick+crash:4 hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_X": ln(
        "snare+crash:4 snare+crash:4 kick+crash:4 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8 "
        "snare+tom-floor-low:4"),   # 1 bar(s), 6 events
    "GROOVE_Y": ln("kick+crash:1"),   # 1 bar(s), 1 events
    "REST2": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "GROOVE_Z": ln("kick+crash:2 kick+crash:2"),   # 1 bar(s), 2 events
    "GROOVE_AA": ln("kick+crash:2 hihat-open:2"),   # 1 bar(s), 2 events
    "GROOVE_AB": ln("hihat-open:2 hihat-open:2 hihat-open:2 hihat-open:2"),   # 2 bar(s), 4 events
    "GROOVE_AC": ln("kick+crash:4 kick+crash:4 kick+crash:4 kick+crash:4"),   # 1 bar(s), 4 events
    "GROOVE_AD": ln(
        "kick+crash:4 kick+crash:4 snare+crash:4 crash:4 kick+crash:4 kick+crash:8 kick:8 "
        "snare+crash:8 kick:8 crash:8 kick:8"),   # 2 bar(s), 11 events
    "GROOVE_AE": ln("kick+crash:4 kick+crash:4 snare+crash:4 crash:4"),   # 1 bar(s), 4 events
    "GROOVE_AF": ln(
        "kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:8 kick:8 hihat-open:8 kick:8 "
        "kick+hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 2 bar(s), 11 events
    "GROOVE_AG": ln("kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:8 kick:8 hihat-open:8 kick:8"),   # 1 bar(s), 7 events
    "GROOVE_AH": ln("kick+hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_AI": ln("snare+crash:4 hihat-open:4 snare+crash:4 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8"),   # 1 bar(s), 5 events
    "GROOVE_AJ": ln(
        "kick+crash:4 kick+hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:4 "
        "kick+hihat-open:8 kick:8 snare+hihat-open:8 kick:8 hihat-open:8 kick:8"),   # 2 bar(s), 11 events
    "GROOVE_AK": ln("kick+hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_AL": ln(
        "kick+hihat-open:4 kick+hihat-open:8 kick:8 snare:8 kick:8 tom-floor-low+tom-low:8 "
        "tom-floor-low+tom-low:8"),   # 1 bar(s), 7 events
    "GROOVE_AM": ln(
        "kick+crash:4 kick+hihat-open:4 snare+crash:4 hihat-open:4 kick+hihat-open:4 "
        "kick+hihat-open:8 kick:8 snare+hihat-open:8 kick:8 hihat-open:8 kick:8"),   # 2 bar(s), 11 events
    "GROOVE_AN": ln("kick+hihat-open:4 kick+hihat-open:4 snare:8 tom-low:T8 tom-low:T8 tom-floor-low:T8 kick:4"),   # 1 bar(s), 7 events
    "REST3": ln("R:1"),   # 1 bar(s), 1 events
    "GROOVE_AO": ln("kick:4 kick:4"),   # 1 bar(s), 2 events
    "GROOVE_AP": ln(
        "kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:8 kick:8 tom-floor-low+tom-low:8 "
        "tom-floor-low+tom-low:8"),   # 1 bar(s), 7 events
    "GROOVE_AQ": ln(
        "kick+hihat-open:4 kick+hihat-open:4 snare+hihat-open:4 snare:16 tom-low:16 tom-low:16 "
        "tom-low:16"),   # 1 bar(s), 7 events
    "GROOVE_AR": ln("kick+crash:4 kick+crash:8 kick:8 snare+crash:8 kick:8 snare+crash:8 snare:8"),   # 1 bar(s), 7 events
    "GROOVE_AS": ln("kick+crash:4 kick+crash:4 snare:8 snare:8 snare:8 snare:8"),   # 1 bar(s), 6 events
    "GROOVE_AT": ln(
        "kick+crash:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 hihat-open:8 "
        "kick+hihat-open:8 kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 "
        "hihat-open:8 kick+hihat-open:8"),   # 2 bar(s), 12 events
    "GROOVE_AU": ln(
        "kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 hihat-open:8 "
        "kick+hihat-open:8"),   # 1 bar(s), 6 events
    "GROOVE_AV": ln(
        "kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:16 kick:16 hihat-open:16 "
        "snare:16 kick+hihat-open:8"),   # 1 bar(s), 8 events
    "GROOVE_AW": ln(
        "kick+hihat-open:8 snare:16 snare:8 snare:16 snare:8 tom-floor-low+tom-low:16 "
        "tom-floor-low+tom-low:16 tom-floor-low+tom-low:8"),   # 1 bar(s), 8 events
    "GROOVE_AX": ln(
        "kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:16 kick:16 hihat-open:16 "
        "kick:16 kick+hihat-open:8"),   # 1 bar(s), 8 events
    "GROOVE_AY": ln(
        "kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 hihat-open:8 "
        "kick+hihat-open:8 kick+hihat-open:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 "
        "hihat-open:8 kick+hihat-open:8"),   # 2 bar(s), 12 events
    "GROOVE_AZ": ln(
        "snare+hihat-open:8 snare+hihat-open:16 kick:16 hihat-open:16 snare:16 snare:16 snare:16 "
        "tom-low:16 tom-low:16 tom-floor-low:16 tom-floor-low:16"),   # 1 bar(s), 11 events
    "GROOVE_BA": ln("kick+crash:4 kick:8 snare+crash:4 kick:8"),   # 1 bar(s), 4 events
    "GROOVE_BB": ln("kick+crash:4 kick:8 snare+crash:8 kick:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_BC": ln(
        "kick+crash:8 hihat-open:8 kick+crash:8 snare:16 tom-low:32 tom-low:32 kick:16 snare:16 "
        "tom-low:16 tom-floor-low:16"),   # 1 bar(s), 10 events
    "GROOVE_BD": ln("kick+crash:8 hihat-open:8 kick+crash:8 snare+crash:8 hihat-open:8 kick+hihat-open:8"),   # 1 bar(s), 6 events
    "GROOVE_BE": ln(
        "kick+crash:8 hihat-open:8 kick+crash:16 kick:16 snare:16 kick:16 crash:16 kick:16 "
        "kick+crash:8"),   # 1 bar(s), 9 events
    "GROOVE_BF": ln(
        "kick+crash:8 hihat-open:8 kick+hihat-open:16 kick:16 snare+crash:8 hihat-open:8 "
        "kick+hihat-open:8"),   # 1 bar(s), 7 events
    "GROOVE_BG": ln(
        "kick+snare+crash:8 snare+tom-floor-low:16 snare+tom-floor-low:16 snare+tom-floor-low:16 "
        "snare+tom-floor-low:16 kick+snare+crash:16 snare+tom-floor-low:16 snare+tom-floor-low:16 "
        "snare+tom-floor-low:16 snare+tom-floor-low:16 snare+tom-floor-low:16"),   # 1 bar(s), 11 events
    "GROOVE_BH": ln("kick+crash:8 hihat-open:8 kick+hihat-open:8 snare+crash:8 hihat-open:8 kick+hihat-open:8"),   # 1 bar(s), 6 events
    "GROOVE_BI": ln(
        "kick+hihat-open:8 snare+hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 hihat-open:8 "
        "kick+hihat-open:16 kick:16"),   # 1 bar(s), 7 events
    "GROOVE_BJ": ln(
        "kick+crash:8 hihat-open:8 kick+hihat-open:8 snare+hihat-open:8 hihat-open:8 "
        "kick+hihat-open:8"),   # 1 bar(s), 6 events
    "GROOVE_BK": ln(
        "kick+hihat-open:8 hihat-open:8 kick+hihat-open:16 kick:16 snare:16 kick:16 snare:16 snare:16 "
        "kick:16 snare:16"),   # 1 bar(s), 10 events
    "GROOVE_BL": ln(
        "kick+crash:8 snare:16 kick:16 crash:16 tom-low:16 crash:16 tom-low:16 tom-low:16 tom-low:16 "
        "tom-low:16 tom-low:16"),   # 1 bar(s), 11 events
    "GROOVE_BM": ln(
        "kick+crash:8 hihat-open:8 kick+crash:8 snare+crash:8 hihat-open:8 kick+crash:8 kick+crash:8 "
        "hihat-open:8"),   # 1 bar(s), 8 events
    "GROOVE_BN": ln("kick+crash:8 snare:8 kick+crash:8 kick+crash:8 kick+crash:8 hihat-open:8"),   # 1 bar(s), 6 events
    "GROOVE_BO": ln(
        "kick+crash:8 snare+hihat-open:8 hihat-open:8 kick+hihat-open:8 kick+hihat-open:8 "
        "snare+hihat-open:16 kick:16 hihat-open:16 snare:16 kick+hihat-open:16 kick:16"),   # 1 bar(s), 11 events
    "GROOVE_BP": ln(
        "snare:16 kick:16 tom-floor-low+tom-low:16 tom-floor-low+tom-low:16 kick+crash:8 hihat-open:8 "
        "kick+crash:8 snare+crash:8"),   # 1 bar(s), 8 events
    "GROOVE_BQ": ln(
        "hihat-open:8 kick:8 kick+hihat-open:4 kick+hihat-open:8 snare:16 kick:16 hihat-open:16 "
        "snare:16 kick+crash:8"),   # 1 bar(s), 9 events
    "GROOVE_BR": ln("kick+crash:4 kick+crash:8 snare+crash:8 hihat-open:8 kick+crash:8"),   # 1 bar(s), 5 events
    "GROOVE_BS": ln(
        "kick+crash:8 kick:16 kick:16 kick:16 kick:16 kick:16 kick:16 kick:16 kick:16 kick+crash:8 "
        "kick+crash:4"),   # 1 bar(s), 11 events
    "GROOVE_BT": ln("hihat-open:4 hihat-open:4 hihat-open:4"),   # 1 bar(s), 3 events
    "GROOVE_BU": ln("hihat-open:4 hihat-open:4 kick+crash:8 kick+crash:8"),   # 1 bar(s), 4 events
    "GROOVE_BV": ln("kick+crash:8 kick+crash:d4 hihat-open:2"),   # 1 bar(s), 3 events
    "GROOVE_BW": ln("hihat-open:2 kick+crash:8 kick+crash:8"),   # 1 bar(s), 3 events
    "GROOVE_BX": ln("kick+crash:4 snare+hihat-open:4 hihat-open:4 snare+hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_BY": ln("hihat-open:4 kick+crash:8 kick+crash:d4"),   # 1 bar(s), 3 events
    "GROOVE_BZ": ln("kick+crash:8 kick+crash:2 kick+crash:8"),   # 1 bar(s), 3 events
    "REST4": ln("R:d2 R:1"),   # 2 bar(s), 2 events
    "REST5": ln("R:d2"),   # 1 bar(s), 1 events
}

DRUMS_SCORE = [
    ("GROOVE_A", 1), ("GROOVE_B", 1), ("GROOVE_C", 1), ("GROOVE_D", 2), ("REST", 1), ("GROOVE_E", 1),
    ("GROOVE_F", 1), ("GROOVE_G", 1), ("GROOVE_H", 3), ("GROOVE_I", 1), ("GROOVE_J", 1), ("GROOVE_K", 1),
    ("GROOVE_L", 1), ("GROOVE_M", 1), ("GROOVE_N", 1), ("GROOVE_O", 1), ("GROOVE_P", 1), ("GROOVE_K", 1),
    ("GROOVE_Q", 1), ("GROOVE_R", 1), ("GROOVE_S", 1), ("GROOVE_T", 1), ("GROOVE_U", 1), ("GROOVE_S", 1),
    ("GROOVE_V", 1), ("GROOVE_W", 1), ("GROOVE_S", 1), ("GROOVE_X", 1), ("GROOVE_Y", 1), ("REST2", 3),
    ("GROOVE_Z", 1), ("GROOVE_AA", 1), ("GROOVE_AB", 3), ("GROOVE_AC", 1), ("GROOVE_AD", 1), ("GROOVE_AE", 1),
    ("GROOVE_AF", 1), ("GROOVE_AG", 1), ("GROOVE_AH", 1), ("GROOVE_AI", 1), ("GROOVE_AJ", 1), ("GROOVE_AK", 1),
    ("GROOVE_AL", 1), ("GROOVE_AM", 1), ("GROOVE_AN", 1), ("GROOVE_AC", 1), ("REST3", 1), ("GROOVE_AO", 1),
    ("GROOVE_AD", 1), ("GROOVE_AK", 1), ("GROOVE_AP", 1), ("GROOVE_AM", 1), ("GROOVE_AQ", 1), ("GROOVE_Z", 1),
    ("GROOVE_AJ", 1), ("GROOVE_AE", 1), ("GROOVE_AR", 1), ("GROOVE_AD", 1), ("GROOVE_AS", 1), ("GROOVE_AC", 1),
    ("GROOVE_AT", 1), ("GROOVE_AU", 1), ("GROOVE_AV", 1), ("GROOVE_AT", 1), ("GROOVE_AU", 1), ("GROOVE_AW", 1),
    ("GROOVE_AT", 1), ("GROOVE_AU", 1), ("GROOVE_AX", 1), ("GROOVE_AY", 1), ("GROOVE_AU", 1), ("GROOVE_AZ", 1),
    ("GROOVE_BA", 1), ("GROOVE_BB", 1), ("GROOVE_BA", 1), ("GROOVE_BC", 1), ("GROOVE_BD", 1), ("GROOVE_BE", 1),
    ("GROOVE_BF", 1), ("GROOVE_BG", 1), ("GROOVE_BH", 1), ("GROOVE_BI", 1), ("GROOVE_BJ", 1), ("GROOVE_BK", 1),
    ("GROOVE_AT", 1), ("GROOVE_BJ", 1), ("GROOVE_BL", 1), ("GROOVE_BM", 1), ("GROOVE_BN", 1), ("GROOVE_BO", 1),
    ("GROOVE_BP", 1), ("GROOVE_BQ", 1), ("GROOVE_BR", 1), ("GROOVE_BS", 1), ("GROOVE_BT", 1), ("GROOVE_BU", 1),
    ("GROOVE_BV", 1), ("GROOVE_BW", 1), ("GROOVE_BX", 1), ("GROOVE_BY", 1), ("REST3", 1), ("GROOVE_BZ", 1),
    ("REST4", 3), ("REST5", 2),
]


# =========================== arrangement / plumbing ===========================
LANES = ('lead', 'rhythm', 'bass', 'drums')
INSTRUMENTS = {
    "lead": "distortion-guitar",
    "rhythm": "distortion-guitar",
    "bass": "electric-bass-pick",
    "drums": "drum-kit",
}
BLOCKS = {
    "lead": LEAD,
    "rhythm": RHYTHM,
    "bass": BASS,
    "drums": DRUMS,
}
SONG_MAPS = {
    "lead": LEAD_SCORE,
    "rhythm": RHYTHM_SCORE,
    "bass": BASS_SCORE,
    "drums": DRUMS_SCORE,
}

TEMPO_MAP = [
    {"beat": 0, "bpm": 115},
    {"beat": 317, "bpm": 110},
    {"beat": 321, "bpm": 115},
    {"beat": 325, "bpm": 113},
    {"beat": 329, "bpm": 114},
    {"beat": 333, "bpm": 115},
    {"beat": 337, "bpm": 114},
    {"beat": 341, "bpm": 115},
    {"beat": 345, "bpm": 114},
    {"beat": 349, "bpm": 115},
    {"beat": 353, "bpm": 116},
    {"beat": 357, "bpm": 115},
    {"beat": 361, "bpm": 116},
    {"beat": 487, "bpm": 58},
    {"beat": 535, "bpm": 59},
]

# Rebuild every lane from its song map; all lanes span the same bars, so they share
# one total length (asserted below) -- no manual rest-padding needed.
timeline = {lane: expand(BLOCKS[lane], SONG_MAPS[lane]) for lane in LANES}

composition = {
    "title": "Monolord - Audhumbla (Recreation)",
    "bpm": 115,
    "time_signature": "4/4",
    "tempo_map": TEMPO_MAP,
    "tracks": [
        {"instrument": INSTRUMENTS[lane], "notes": timeline[lane]} for lane in LANES
    ],
}


if __name__ == "__main__":
    total = beats(timeline[LANES[0]])
    for lane in LANES:
        assert abs(beats(timeline[lane]) - total) < 1e-6, \
            f"{lane} misaligned ({beats(timeline[lane])} vs {total})"
    print(f"Title : Monolord - Audhumbla (Recreation)")
    print(f"Lanes : {', '.join(LANES)}")
    print(f"Length: {total:.0f} beats")
    print("Blocks: " + ", ".join(f"{l}={len(BLOCKS[l])}" for l in LANES))
    nev = sum(len(t["notes"]) for t in composition["tracks"])
    print(f"Events: {nev} notes/chords across {len(composition['tracks'])} tracks")
    path = generate_midi_from_dict(composition)
    print(f"MIDI written: {path}")
    stem = Path(path).stem
    print(f'Render to WAV:  python render_wav.py 0.7 "{stem}"')
