#!/usr/bin/env python3
"""
Monolord - Empress Rising - IA full Drums (Recreation)
=== a FAITHFUL recreation of a real doom song, written in the compose_doom_*.py idiom ===

Auto-generated by transcribe_song.py / analysis.extract_blocks from the Guitar Pro tab,
then iterable like compose_doom_drowned_cathedral.py. Each lane is expressed as named,
reusable BLOCKS (riffs / grooves / pedals / rests) plus a flat SONG MAP -- a
`[(block, count), ...]` score that cycles those blocks to rebuild the whole part. Tweak
a block, or re-order / re-count a song map, to spin a new piece off this structure.

  Key/feel : B Phrygian, 128 BPM, 352 bars / 1450 beats
  Lanes    : lead=distortion-guitar, rhythm=distortion-guitar, bass=electric-bass-pick, vox=tenor-sax, drums=drum-kit

FAITHFUL on pitch, voicing, rhythm, every drum hit, the tempo map and the arrangement.
NOT reproduced: per-note velocity (absent from the source IR -> flat) and notated meter
changes (kept as a global 4/4 -- audio is unaffected since durations are absolute beats).
"""

import sys
from pathlib import Path

REPO = Path(__file__).parent
sys.path.insert(0, str(REPO))

from skills.generate_midi import generate_midi_from_dict, parse_duration


def ln(s):
    """Compact "P:dur P:dur ..." note string -> [('pitch', 'duration'), ...].

    `P` is a pitch (`B1`), a chord (`B2+Gb3+B3`), a drum name, or a rest (`R`);
    `dur` is a skill duration token (`2`, `d4`, `T8`). Whitespace-separated, so a
    block that took dozens of dict lines is one readable string here.
    """
    return [dict(zip(("pitch", "duration"), t.rsplit(":", 1))) for t in s.split()]


def expand(blocks, score):
    """A lane's [(block_name, count), ...] song map -> a flat list of note dicts."""
    out = []
    for name, count in score:
        out += blocks[name] * count
    return out


def beats(notes):
    return sum(parse_duration(n["duration"]) for n in notes)


# ===================== LEAD blocks (distortion-guitar) =====================
LEAD = {
    "RIFF_A": ln("B1:2 B2+Gb3+B3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4"),   # 2 bar(s), 8 events
    "RIFF_B": ln("B1:2 B2+Gb3+B3:d4 B1:8"),   # 1 bar(s), 3 events
    "RIFF_C": ln("E3:8 B2:8 C3:4 A3:4 B3:4"),   # 1 bar(s), 5 events
    "RIFF_D": ln("B3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 1 bar(s), 5 events
    "RIFF_E": ln("B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4"),   # 4 bar(s), 16 events
    "RIFF_F": ln("B1:2 Gb3+B3:d4 B1:8"),   # 1 bar(s), 3 events
    "RIFF_G": ln("E3+A3:8 B2:8 C3:4 E3+A3:4 B2:4"),   # 1 bar(s), 5 events
    "RIFF_H": ln("E3+A3:8 B2:8 B2:8 C3:8 E3+A3:4 B2:8 C3:8"),   # 1 bar(s), 7 events
    "RIFF_I": ln("B2:4 B1:4 Gb3+B3:d4 B1:8"),   # 1 bar(s), 4 events
    "RIFF_J": ln("E3:8 Gb3:8 B2:8 C3:8 E3:4 B2:4"),   # 1 bar(s), 6 events
    "RIFF_K": ln("B1:2 Gb3:d4 B1:8 E3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 2 bar(s), 8 events
    "RIFF_L": ln("E3:8 B2:8 C3:4 E3:4 B2:8 C3:8"),   # 1 bar(s), 6 events
    "RIFF_M": ln("B2:4 B1:4 B2+Gb3+B3:d4 B1:8"),   # 1 bar(s), 4 events
    "RIFF_N": ln("E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8"),   # 4 bar(s), 16 events
    "RIFF_O": ln("E3:8 B2:8 C3:4 E3:4 B2:4 R:1 R:1 R:1"),   # 4 bar(s), 8 events
    "REST": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "RIFF_P": ln("E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 B2+Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 B2+Gb3:d4 B1:8"),   # 4 bar(s), 16 events
    "RIFF_Q": ln("E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 B2+Gb3:d4 B1:8"),   # 2 bar(s), 8 events
    "RIFF_R": ln("E3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 1 bar(s), 5 events
    "PEDAL": ln("B2:1"),   # 1 bar(s), 1 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST3": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
    "RIFF_S": ln("B1+Gb2:2 B2+Gb3:2"),   # 1 bar(s), 2 events
    "RIFF_T": ln("E3:8 Gb3:8 G3:4 E3:4 D3:4"),   # 1 bar(s), 5 events
    "RIFF_U": ln(
        "B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 R:1 R:1 R:1 "
        "R:1 R:1"),   # 8 bar(s), 14 events
    "RIFF_V": ln("B1:2 B2+Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4"),   # 2 bar(s), 8 events
    "RIFF_W": ln("B1:2 B2+Gb3:d4 B1:8"),   # 1 bar(s), 3 events
    "RIFF_X": ln("E3:8 B2:8 C3:4 B2:4 R:4"),   # 1 bar(s), 5 events
    "RIFF_Y": ln("B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 D3:8 D3:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 4 bar(s), 16 events
    "RIFF_Z": ln("B1:2 B2:2 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 17 events
    "RIFF_AA": ln("B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 4 bar(s), 16 events
    "RIFF_AB": ln("B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 2 bar(s), 8 events
    "RIFF_AC": ln("B1+Gb2:2 B2:2"),   # 1 bar(s), 2 events
    "RIFF_AD": ln("A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 1 bar(s), 6 events
    "RIFF_AE": ln("B1+Gb2:2 B2:4 B2:8 A2:8"),   # 1 bar(s), 4 events
    "RIFF_AF": ln("B2:8 F2:d4 F2:8 D2:d4"),   # 1 bar(s), 4 events
    "REST5": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "RIFF_AG": ln("R:1 R:1 R:1 B1+Gb2:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "RIFF_AH": ln("E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4"),   # 2 bar(s), 8 events
    "RIFF_AI": ln("E3:4 B2:4 B1:2"),   # 1 bar(s), 3 events
    "RIFF_AJ": ln("B1:2 Gb3:d4 B1:8"),   # 1 bar(s), 3 events
    "RIFF_AK": ln("E3:4 B2:8 C3:8 B2:4 B1:4"),   # 1 bar(s), 5 events
    "RIFF_AL": ln("Gb3:d4 B1:8 E3:8 Gb3:8 C3:4 E3:4 C3:4"),   # 1 bar(s), 7 events
    "REST6": ln("R:1 R:1 R:2"),   # 2 bar(s), 3 events
    "RIFF_AM": ln("A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2"),   # 4 bar(s), 16 events
    "RIFF_AN": ln("A2:8 B2:8 B2:4 B2:8 A2:8 A2:4"),   # 1 bar(s), 6 events
    "RIFF_AO": ln("B1:2 B2:4 B1:8 B1:8 C2:4 B1:4"),   # 1 bar(s), 6 events
    "RIFF_AP": ln("F2:2 F2:4 D2:8 D2:8 E2:4 C2:4"),   # 1 bar(s), 6 events
    "REST7": ln("R:1 R:2 R:1 R:1 R:1 R:2 R:1 R:2 R:1 R:2 R:1 R:1"),   # 8 bar(s), 12 events
    "RIFF_AQ": ln("B1+Gb2:2 B2:4 B1:8 B1:8 C2+G2:4 B1+Gb2:4"),   # 1 bar(s), 6 events
    "RIFF_AR": ln("F2+C3:2 F2+C3:4 D2+A2:8 D2+A2:8 E2+B2:4 C2+G2:4"),   # 1 bar(s), 6 events
    "REST8": ln("R:1 R:2 R:1"),   # 2 bar(s), 3 events
    "REST9": ln("R:1 R:1 R:4 R:1 R:2 R:1 R:4"),   # 4 bar(s), 7 events
    "REST10": ln("R:1 R:4 R:1 R:2"),   # 2 bar(s), 4 events
    "REST11": ln("R:1 R:4"),   # 1 bar(s), 2 events
    "REST12": ln("R:2"),   # 1 bar(s), 1 events
    "REST13": ln("R:1 R:1 R:1 R:2 R:1 R:2"),   # 4 bar(s), 6 events
    "RIFF_AS": ln("R:1 B1+Gb2:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "PEDAL2": ln("B1:2 B2:2"),   # 1 bar(s), 2 events
    "RIFF_AT": ln("B1:8 B2:8 B1:8 C3:4 E3:4 B2:8"),   # 1 bar(s), 6 events
    "PEDAL3": ln("C4:1"),   # 1 bar(s), 1 events
    "PEDAL4": ln("R:d2 B3:8 R:8"),   # 1 bar(s), 3 events
    "RIFF_AU": ln("B3:2 G4:2"),   # 1 bar(s), 2 events
    "RIFF_AV": ln("A4:4 A4:4 A4:4 A4:4 A4:4 A4:4 A4:4 A4:4"),   # 2 bar(s), 8 events
    "RIFF_AW": ln("B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4"),   # 2 bar(s), 7 events
    "RIFF_AX": ln(
        "A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 "
        "A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 A3:16 "
        "A3:16 A3:16"),   # 2 bar(s), 32 events
    "RIFF_AY": ln("B1+Gb2+B2:1"),   # 1 bar(s), 1 events
    "RIFF_AZ": ln("A4+Bb4:1"),   # 1 bar(s), 1 events
    "PEDAL5": ln("B1:1"),   # 1 bar(s), 1 events
}

LEAD_SCORE = [
    ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_C", 1), ("RIFF_B", 1), ("RIFF_D", 1), ("RIFF_E", 1),
    ("RIFF_F", 1), ("RIFF_G", 1), ("RIFF_F", 1), ("RIFF_H", 1), ("RIFF_I", 1), ("RIFF_J", 1),
    ("RIFF_K", 2), ("RIFF_A", 1), ("RIFF_B", 1), ("RIFF_L", 1), ("RIFF_M", 1), ("RIFF_N", 1),
    ("RIFF_O", 1), ("REST", 1), ("RIFF_N", 1), ("RIFF_P", 1), ("RIFF_Q", 1), ("RIFF_R", 1),
    ("PEDAL", 1), ("REST2", 1), ("REST3", 1), ("REST", 1), ("REST4", 1), ("RIFF_S", 1),
    ("RIFF_T", 1), ("RIFF_U", 1), ("RIFF_V", 1), ("RIFF_W", 1), ("RIFF_X", 1), ("REST3", 1),
    ("REST", 1), ("RIFF_Y", 1), ("RIFF_Z", 1), ("RIFF_AA", 1), ("RIFF_Y", 1), ("RIFF_AB", 1),
    ("RIFF_AC", 1), ("RIFF_AD", 1), ("RIFF_AE", 1), ("RIFF_AF", 1), ("RIFF_AC", 1), ("REST5", 1),
    ("REST3", 1), ("RIFF_AG", 1), ("REST3", 1), ("RIFF_AH", 2), ("RIFF_AI", 1), ("RIFF_E", 1),
    ("RIFF_AJ", 1), ("RIFF_AK", 1), ("RIFF_AL", 1), ("REST2", 1), ("REST3", 1), ("REST6", 1),
    ("REST", 1), ("REST4", 1), ("RIFF_AM", 1), ("RIFF_AN", 1), ("RIFF_AA", 1), ("RIFF_Z", 1),
    ("REST2", 1), ("REST3", 1), ("RIFF_AO", 1), ("RIFF_AP", 1), ("REST7", 1), ("RIFF_AQ", 1),
    ("RIFF_AR", 1), ("REST8", 1), ("REST9", 1), ("REST8", 1), ("REST10", 1), ("REST11", 1),
    ("REST12", 1), ("REST13", 1), ("REST7", 1), ("RIFF_AS", 1), ("PEDAL2", 1), ("RIFF_AT", 1),
    ("PEDAL2", 1), ("RIFF_P", 1), ("RIFF_O", 1), ("REST2", 1), ("REST3", 1), ("REST", 1),
    ("PEDAL3", 1), ("PEDAL4", 1), ("RIFF_AU", 1), ("REST3", 1), ("REST4", 1), ("RIFF_AV", 2),
    ("RIFF_AW", 1), ("RIFF_U", 1), ("RIFF_AX", 2), ("RIFF_AY", 1), ("REST5", 1), ("REST", 1),
    ("REST4", 1), ("RIFF_AZ", 1), ("REST", 1), ("REST4", 1), ("PEDAL5", 1), ("REST4", 1),
]

# ===================== RHYTHM blocks (distortion-guitar) =====================
RHYTHM = {
    "REST": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST2": ln("R:1"),   # 1 bar(s), 1 events
    "RIFF_A": ln("B3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 1 bar(s), 5 events
    "RIFF_B": ln("B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4"),   # 4 bar(s), 16 events
    "RIFF_C": ln("E3:8 Gb3:8 B2:8 C3:8 E3:4 B2:4"),   # 1 bar(s), 6 events
    "RIFF_D": ln("B1:2 Gb3:d4 B1:8 E3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 2 bar(s), 8 events
    "RIFF_E": ln("E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 Gb3:d4 B1:8"),   # 4 bar(s), 16 events
    "RIFF_F": ln("E3:8 B2:8 C3:4 E3:4 B2:4"),   # 1 bar(s), 5 events
    "RIFF_G": ln("B1:2 B2+Gb3+B3:d4 B1:8 E3+A3:8 B2:8 C3:4 E3:4 B2:4"),   # 2 bar(s), 8 events
    "RIFF_H": ln("B1:2 B2+Gb3+B3:d4 B1:8"),   # 1 bar(s), 3 events
    "RIFF_I": ln("E3:8 B2:8 C3:4 E3:4 B2:4 B1:2 B2+Gb3:d4 B1:8"),   # 2 bar(s), 8 events
    "RIFF_J": ln("E3:8 Gb3:8 C3:4 E3:4 B2:4"),   # 1 bar(s), 5 events
    "PEDAL": ln("B2:1"),   # 1 bar(s), 1 events
    "RIFF_K": ln(
        "R:1 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 "
        "B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2"),   # 16 bar(s), 52 events
    "RIFF_L": ln(
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2"),   # 8 bar(s), 28 events
    "RIFF_M": ln("D2+A2:8 E2+B2:8 F2+C3:4 A2+E3:4 D2+A2:4"),   # 1 bar(s), 5 events
    "RIFF_N": ln(
        "B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 "
        "B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4"),   # 8 bar(s), 28 events
    "RIFF_O": ln("B2+Gb3:2 B2+Gb3:2"),   # 1 bar(s), 2 events
    "RIFF_P": ln("A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2"),   # 4 bar(s), 16 events
    "RIFF_Q": ln("A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 D3:8 D3:4 B1:2 B2:2"),   # 4 bar(s), 16 events
    "RIFF_R": ln(
        "A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 "
        "B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:4 B2:8 A2:8 B2:8 F2:d4 F2:8 D2:d4 B1+Gb2:2 B2+Gb3:2"),   # 8 bar(s), 32 events
    "RIFF_S": ln(
        "A2+E3:8 B2+Gb3:8 B2+Gb3:4 B2+Gb3:8 Bb2+F3:8 Bb2+F3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 "
        "B2+Gb3:4 B2+Gb3:8 Bb2+F3:8 Bb2+F3:4 B1+Gb2:2 B2+Gb3:2"),   # 4 bar(s), 16 events
    "RIFF_T": ln("A2+E3:8 B2+Gb3:8 B2+Gb3:4 B2+Gb3:8 Bb2+F3:8 Bb2+F3:4"),   # 1 bar(s), 6 events
    "RIFF_U": ln(
        "B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 "
        "B2:2 A2:8 B2:8 B2:4 B2:8 D3:8 D3:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 8 bar(s), 32 events
    "RIFF_V": ln("B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 2 bar(s), 8 events
    "RIFF_W": ln("B1+Gb2:2 B2:2"),   # 1 bar(s), 2 events
    "RIFF_X": ln("A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4"),   # 1 bar(s), 6 events
    "RIFF_Y": ln("B1+Gb2:2 B2:4 B2:8 A2:8"),   # 1 bar(s), 4 events
    "RIFF_Z": ln("B2:8 F2:d4 F2:8 D2:d4"),   # 1 bar(s), 4 events
    "RIFF_AA": ln(
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2"),   # 4 bar(s), 14 events
    "RIFF_AB": ln("A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2"),   # 2 bar(s), 7 events
    "RIFF_AC": ln("A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4"),   # 1 bar(s), 5 events
    "RIFF_AD": ln("B1+Gb2:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "RIFF_AE": ln("B1+Gb2+B2:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "RIFF_AF": ln("E3:4 B2:4 B1:2 Gb3:d4 B1:8 E3:8 B2:8 C3:4"),   # 2 bar(s), 8 events
    "RIFF_AG": ln("E3:4 B2:4 B1:2"),   # 1 bar(s), 3 events
    "RIFF_AH": ln("B1:2 Gb3:d4 B1:8"),   # 1 bar(s), 3 events
    "REST3": ln("R:1 R:2"),   # 1 bar(s), 2 events
    "RIFF_AI": ln(
        "B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 "
        "B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4"),   # 16 bar(s), 56 events
    "RIFF_AJ": ln(
        "B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 "
        "B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4"),   # 4 bar(s), 14 events
    "RIFF_AK": ln("B1+Gb2:2 B2+Gb3:2"),   # 1 bar(s), 2 events
    "RIFF_AL": ln("A2+E3:8 B2+Gb3:8 C3+G3:4 R:1"),   # 1 bar(s), 4 events
    "RIFF_AM": ln("B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 B2+Gb3:4 B2+Gb3:8 Bb2+F3:8 Bb2+F3:4"),   # 2 bar(s), 8 events
    "RIFF_AN": ln("A2:8 B2:8 B2:4 B2:8 A2:8 A2:4"),   # 1 bar(s), 6 events
    "RIFF_AO": ln(
        "B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 "
        "B2:2 A2:8 B2:8 B2:4 B2:8 Bb2:8 Bb2:4 B1:2 B2:4 B2:8 A2:8 B2:8 F2:d4 F2:8 D2:d4"),   # 8 bar(s), 32 events
    "RIFF_AP": ln("B1:2 B2:4 B1:8 B1:8 C2:4 B1:4 F2:2 F2:4 D2:8 D2:8 E2:4 C2:4"),   # 2 bar(s), 12 events
    "RIFF_AQ": ln("B1:2 B2+Gb3:4 B1:8 B1:8 C2:4 B1:4"),   # 1 bar(s), 6 events
    "PEDAL2": ln("Bb2:d2 Bb2:8 Bb2:8"),   # 1 bar(s), 3 events
    "RIFF_AR": ln("A2:8 G2:8 A2:4 A2:16 Bb2:16 A2:d4"),   # 1 bar(s), 6 events
    "RIFF_AS": ln("B1:2 B2:4 B1:8 B1:8 C2:4 B1:4"),   # 1 bar(s), 6 events
    "RIFF_AT": ln("A2:8 G2:8 A2:4 Bb2+F3:8 A2+E3:d4"),   # 1 bar(s), 5 events
    "RIFF_AU": ln("B1+Gb2:2 B2:4 B1:8 B1:8 C2+G2:4 B1+Gb2:4"),   # 1 bar(s), 6 events
    "RIFF_AV": ln(
        "F2+C3:2 F2+C3:4 D2+A2:8 D2+A2:8 E2+B2:4 C2+G2:4 B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8 C2+G2:4 "
        "B1+Gb2:4 Bb2+F3:2 Bb2+F3:4 Bb2+F3:8 Bb2+F3:8 A2+E3:8 G2+D3:8 A2+E3:4 Bb2+F3:8 A2+E3:d4"),   # 4 bar(s), 21 events
    "RIFF_AW": ln("B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8 C2+G2:4 B1+Gb2:4 F2+C3:2 F2+C3:4 D2+A2:8 D2+A2:8 E2+B2:4"),   # 2 bar(s), 11 events
    "RIFF_AX": ln("C2+G2:4 B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8"),   # 1 bar(s), 5 events
    "RIFF_AY": ln("C2+G2:4 B1+Gb2:4 Bb2+F3:2 Bb2+F3:4 Bb2+F3:8 Bb2+F3:8"),   # 1 bar(s), 6 events
    "RIFF_AZ": ln(
        "A2+E3:8 G2+D3:8 A2+E3:4 Bb2+F3:8 A2+E3:d4 B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8 C2+G2:4 B1+Gb2:4 "
        "F2+C3:2 F2+C3:4 D2+A2:8 D2+A2:8 E2+B2:4 C2+G2:4 B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8"),   # 4 bar(s), 21 events
    "RIFF_BA": ln("C2+G2:4 B1+Gb2:4"),   # 1 bar(s), 2 events
    "RIFF_BB": ln("Bb2+F3:2 Bb2+F3:4 Bb2+F3:8 Bb2+F3:8 A2+E3:8 G2+D3:8 A2+E3:4 Bb2+F3:8 A2+E3:d4"),   # 2 bar(s), 9 events
    "RIFF_BC": ln("B1+Gb2:2 B2:T8 C3:T8 B2:T8 C3:T8 B2:T8 C3:T8 B1+Gb2:8 B1+Gb2:8 C2+G2:4 B1+Gb2:4"),   # 1 bar(s), 11 events
    "RIFF_BD": ln("B1+Gb2:2 B2:4 B1+Gb2:8 B1+Gb2:8 C2+G2:4 B1+Gb2:4"),   # 1 bar(s), 6 events
    "REST4": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "RIFF_BE": ln("B1+E2+A2:1"),   # 1 bar(s), 1 events
    "RIFF_BF": ln(
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 "
        "A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 B2+Gb3:4 B1+Gb2:2 B2+Gb3:2 A2+E3:8 B2+Gb3:8 C3+G3:4 A2+E3:4 "
        "B2+Gb3:4 B1+Gb2:2 B2+Gb3:2"),   # 16 bar(s), 56 events
    "RIFF_BG": ln("R:4 B1+Gb2:d2"),   # 1 bar(s), 2 events
    "RIFF_BH": ln("R:1 B1+Gb2+B2:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST5": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "RIFF_BI": ln("B1+Gb2+B2:1"),   # 1 bar(s), 1 events
}

RHYTHM_SCORE = [
    ("REST", 1), ("REST2", 1), ("RIFF_A", 1), ("RIFF_B", 1), ("REST", 1), ("REST2", 1),
    ("RIFF_C", 1), ("RIFF_D", 2), ("REST", 1), ("REST2", 1), ("RIFF_E", 1), ("RIFF_F", 1),
    ("RIFF_G", 2), ("RIFF_H", 1), ("RIFF_E", 1), ("RIFF_I", 3), ("RIFF_J", 1), ("PEDAL", 1),
    ("RIFF_K", 1), ("RIFF_L", 1), ("RIFF_M", 1), ("RIFF_N", 1), ("REST", 1), ("RIFF_O", 1),
    ("RIFF_P", 1), ("RIFF_Q", 1), ("RIFF_R", 1), ("RIFF_S", 2), ("RIFF_T", 1), ("RIFF_U", 1),
    ("RIFF_V", 1), ("RIFF_W", 1), ("RIFF_X", 1), ("RIFF_Y", 1), ("RIFF_Z", 1), ("RIFF_W", 1),
    ("RIFF_L", 1), ("RIFF_AA", 1), ("RIFF_AB", 1), ("RIFF_AC", 1), ("RIFF_AD", 1), ("RIFF_AE", 1),
    ("REST2", 1), ("RIFF_AF", 2), ("RIFF_AG", 1), ("RIFF_B", 1), ("RIFF_AH", 1), ("REST2", 1),
    ("REST3", 1), ("RIFF_AI", 1), ("RIFF_AJ", 1), ("RIFF_AK", 1), ("RIFF_AL", 1), ("RIFF_AM", 1),
    ("RIFF_AK", 1), ("RIFF_P", 1), ("RIFF_AN", 1), ("RIFF_AO", 1), ("RIFF_AI", 2), ("RIFF_AP", 1),
    ("RIFF_AQ", 1), ("PEDAL2", 1), ("RIFF_AR", 1), ("RIFF_AP", 1), ("RIFF_AS", 1), ("PEDAL2", 1),
    ("RIFF_AT", 1), ("RIFF_AU", 1), ("RIFF_AV", 1), ("RIFF_AW", 1), ("RIFF_AX", 1), ("RIFF_AY", 1),
    ("RIFF_AZ", 1), ("RIFF_BA", 1), ("RIFF_BB", 1), ("RIFF_BC", 1), ("RIFF_AV", 1), ("RIFF_BD", 1),
    ("RIFF_AV", 1), ("RIFF_AD", 1), ("REST", 1), ("REST4", 1), ("REST2", 1), ("RIFF_BE", 1),
    ("REST", 1), ("RIFF_K", 1), ("RIFF_BF", 2), ("RIFF_AC", 1), ("RIFF_BG", 1), ("RIFF_BH", 1),
    ("REST5", 1), ("REST", 1), ("REST4", 1), ("RIFF_BI", 1),
]

# ===================== BASS blocks (electric-bass-pick) =====================
BASS = {
    "REST": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST2": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST3": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST4": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "RIFF_A": ln("B0:2 B0:4 B0:8 B0:8 B0:8 B0:8 B0:4 B0:4 B0:4"),   # 2 bar(s), 9 events
    "PEDAL": ln("B0:2 B0:4 B0:8 B0:8"),   # 1 bar(s), 4 events
    "RIFF_B": ln(
        "R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 "
        "B1:2"),   # 16 bar(s), 22 events
    "RIFF_C": ln(
        "A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 "
        "B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 "
        "B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 "
        "B0:2 B1:2"),   # 16 bar(s), 56 events
    "RIFF_D": ln(
        "A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 "
        "B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 "
        "B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:1 R:1 R:1"),   # 16 bar(s), 50 events
    "RIFF_E": ln("R:1 B0:2 B1:2"),   # 2 bar(s), 3 events
    "RIFF_F": ln("A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2"),   # 4 bar(s), 16 events
    "RIFF_G": ln("A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2"),   # 2 bar(s), 8 events
    "RIFF_H": ln("A1:8 B1:8 B1:4 B1:8 A1:8 A1:4"),   # 1 bar(s), 6 events
    "RIFF_I": ln(
        "B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 "
        "B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:4 B1:8 A1:8 B1:8 F1:d4 F1:8 D1:d4"),   # 8 bar(s), 32 events
    "RIFF_J": ln(
        "B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 "
        "B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4"),   # 8 bar(s), 32 events
    "RIFF_K": ln(
        "B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 "
        "B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 "
        "A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:2 A1:8 "
        "B1:8 B1:4 B1:8 Bb1:8 Bb1:4 B0:2 B1:4 B1:8 A1:8 B1:8 F1:d4 F1:8 D1:d4"),   # 16 bar(s), 64 events
    "RIFF_L": ln(
        "B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 "
        "C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 "
        "B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 "
        "A1:4 B1:4"),   # 16 bar(s), 56 events
    "RIFF_M": ln("B0:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST5": ln("R:1 R:2"),   # 1 bar(s), 2 events
    "RIFF_N": ln("B0:1 R:1 R:2 B1:2 R:1"),   # 4 bar(s), 5 events
    "REST6": ln("R:1"),   # 1 bar(s), 1 events
    "RIFF_O": ln("A1:8 B1:8 C2:2 R:4"),   # 1 bar(s), 4 events
    "RIFF_P": ln("A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2"),   # 4 bar(s), 14 events
    "RIFF_Q": ln("A1:8 B1:8 C2:4 A1:4 B1:4 B0:1"),   # 2 bar(s), 6 events
    "RIFF_R": ln("R:1 B0:1"),   # 2 bar(s), 2 events
    "RIFF_S": ln("R:1 R:2 B1:2"),   # 2 bar(s), 3 events
    "RIFF_T": ln("A1:8 B1:8 C2:2 R:d2"),   # 1 bar(s), 4 events
    "RIFF_U": ln(
        "B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 F1:2 F1:4 D1:8 D1:8 E1:4 C1:4 B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 "
        "Bb1:2 Bb1:4 Bb1:8 Bb1:8"),   # 4 bar(s), 22 events
    "RIFF_V": ln(
        "A1:8 G1:8 A1:4 Bb1:8 A1:d4 B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 F1:2 F1:4 D1:8 D1:8 E1:4 C1:4 B0:2 "
        "B1:4 B0:8 B0:8 C1:4 B0:4"),   # 4 bar(s), 23 events
    "PEDAL2": ln("Bb1:2 Bb1:4 Bb1:8 Bb1:8"),   # 1 bar(s), 4 events
    "RIFF_W": ln("A1:8 G1:8 A1:4 Bb1:8 A1:8 A1:4"),   # 1 bar(s), 6 events
    "RIFF_X": ln("B0:2 B1:4 B0:8 B0:8 C1:4 B0:4"),   # 1 bar(s), 6 events
    "RIFF_Y": ln("F1:2 F1:4 D1:4 E1:4 C1:4"),   # 1 bar(s), 5 events
    "RIFF_Z": ln("B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 Bb1:2 Bb1:4 Bb1:8 Bb1:8"),   # 2 bar(s), 10 events
    "RIFF_AA": ln(
        "A1:8 G1:8 A1:4 Bb1:8 A1:d4 B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 F1:2 F1:4 D1:8 D1:8 E1:4 C1:4 B0:2 "
        "B1:4 B0:8 B0:8"),   # 4 bar(s), 21 events
    "RIFF_AB": ln("C1:4 B0:4 Bb1:2 Bb1:4 Bb1:8 Bb1:8"),   # 1 bar(s), 6 events
    "RIFF_AC": ln("C1:4 B0:4"),   # 1 bar(s), 2 events
    "RIFF_AD": ln(
        "Bb1:2 Bb1:4 Bb1:8 Bb1:8 A1:8 G1:8 A1:4 Bb1:8 A1:d4 B0:2 B1:4 B0:8 B0:8 C1:4 B0:4 F1:2 F1:4 "
        "D1:8 D1:8 E1:4 C1:4"),   # 4 bar(s), 21 events
    "RIFF_AE": ln("B0:2 C2:4 B0:8 B0:8 C1:4 B0:4"),   # 1 bar(s), 6 events
    "RIFF_AF": ln("A1:8 G1:8 A1:4 Bb1:8 A1:d4"),   # 1 bar(s), 5 events
    "RIFF_AG": ln(
        "R:1 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 "
        "B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 "
        "B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2 A1:8 B1:8 C2:4 A1:4 B1:4 B0:2 B1:2"),   # 16 bar(s), 52 events
    "RIFF_AH": ln("A1:8 B1:8 C2:4 A1:4 B0:4"),   # 1 bar(s), 5 events
    "RIFF_AI": ln("B0:1 R:1"),   # 2 bar(s), 2 events
}

BASS_SCORE = [
    ("REST", 1), ("REST2", 1), ("REST3", 1), ("REST4", 1), ("RIFF_A", 2), ("PEDAL", 1),
    ("RIFF_B", 1), ("RIFF_C", 1), ("RIFF_D", 1), ("RIFF_E", 1), ("RIFF_F", 1), ("RIFF_G", 1),
    ("RIFF_H", 1), ("RIFF_I", 1), ("RIFF_J", 1), ("RIFF_K", 1), ("RIFF_L", 1), ("RIFF_M", 1),
    ("REST3", 1), ("REST5", 1), ("RIFF_N", 1), ("REST6", 1), ("RIFF_O", 1), ("REST6", 1),
    ("RIFF_P", 1), ("RIFF_Q", 1), ("RIFF_R", 2), ("RIFF_S", 2), ("RIFF_T", 1), ("RIFF_K", 1),
    ("RIFF_L", 2), ("RIFF_U", 1), ("RIFF_V", 1), ("PEDAL2", 1), ("RIFF_W", 1), ("RIFF_X", 1),
    ("RIFF_Y", 1), ("RIFF_Z", 1), ("RIFF_AA", 1), ("RIFF_AB", 1), ("RIFF_AA", 1), ("RIFF_AC", 1),
    ("RIFF_AD", 1), ("RIFF_AE", 1), ("RIFF_AD", 1), ("RIFF_Z", 1), ("RIFF_AF", 1), ("RIFF_M", 1),
    ("RIFF_AG", 1), ("RIFF_C", 2), ("RIFF_AH", 1), ("RIFF_M", 1), ("REST4", 1), ("RIFF_AI", 1),
]

# ===================== VOX blocks (tenor-sax) =====================
VOX = {
    "REST": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST2": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST3": ln("R:1"),   # 1 bar(s), 1 events
    "PHRASE_A": ln("B3:4 B3:4 B3:8 Bb3:d4"),   # 1 bar(s), 4 events
    "PEDAL": ln("R:4 B3:8 B3:8 B3:4 B3:4"),   # 1 bar(s), 5 events
    "PEDAL2": ln("R:2 B3:4 B3:4"),   # 1 bar(s), 3 events
    "PHRASE_B": ln("R:4 B3:4 B3:4 B3:4 B3:8 B3:8 C4:4 B3:4 R:4"),   # 2 bar(s), 9 events
    "PEDAL3": ln("R:4 B3:4 B3:4 B3:4"),   # 1 bar(s), 4 events
    "PEDAL4": ln("B3:8 B3:8 B3:4 B3:d4 R:8"),   # 1 bar(s), 5 events
    "PHRASE_C": ln("B3:4 B3:4 B3:4 B3:4 B3:4 B3:4 B3:4 B3:4"),   # 2 bar(s), 8 events
    "PHRASE_D": ln("B3:4 B3:4 B3:4 B3:4 C4:4 C4:4 C4:8 B3:d4"),   # 2 bar(s), 8 events
    "PEDAL5": ln("B3:2 R:2"),   # 1 bar(s), 2 events
    "REST4": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "PEDAL6": ln("B3:4 B3:4 B3:4 R:4"),   # 1 bar(s), 4 events
    "PHRASE_E": ln("C4:4 B3:4 C4:8 B3:d4"),   # 1 bar(s), 4 events
    "PHRASE_F": ln("C4:4 B3:4 Bb3:2"),   # 1 bar(s), 3 events
    "PEDAL7": ln("B3:4 B3:4 B3:4 B3:4"),   # 1 bar(s), 4 events
    "PEDAL8": ln("C4:8 C4:8 C4:4 C4:8 C4:8 C4:4"),   # 1 bar(s), 6 events
    "PEDAL9": ln("B3:4 B3:4 B3:4 B3:8 B3:8"),   # 1 bar(s), 5 events
    "PHRASE_G": ln("C4:8 C4:d4 C4:4 B3:4"),   # 1 bar(s), 4 events
    "PHRASE_H": ln("R:2 R:2 R:2 C4:4 C4:4 C4:4 B3:d2 R:1 R:1 R:2 C4:4 C4:4 C4:4 B3:d2 R:1"),   # 8 bar(s), 15 events
    "PHRASE_I": ln("R:1 R:2 C4:4 C4:4 C4:4 B3:d2 R:1"),   # 4 bar(s), 7 events
    "PHRASE_J": ln("R:1 R:2 C4:4 C4:4"),   # 2 bar(s), 4 events
    "PHRASE_K": ln("C4:2 C4:4 C4:8 B3:8"),   # 1 bar(s), 4 events
    "PHRASE_L": ln("B3:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST5": ln("R:1 R:1 R:2"),   # 2 bar(s), 3 events
    "PEDAL10": ln("B3:4 B3:8 B3:8 B3:8 B3:8 B3:4"),   # 1 bar(s), 6 events
    "PHRASE_M": ln("B3:4 B3:4 Bb3:4 Bb3:4"),   # 1 bar(s), 4 events
    "PHRASE_N": ln("C4:4 C4:4 C4:8 B3:8 B3:4"),   # 1 bar(s), 5 events
    "PEDAL11": ln("B3:d2 R:4"),   # 1 bar(s), 2 events
    "PHRASE_O": ln("C4:8 C4:8 C4:4 C4:8 B3:d4"),   # 1 bar(s), 5 events
    "PHRASE_P": ln("C4:d2 B3:4 B3:1"),   # 2 bar(s), 3 events
    "PHRASE_Q": ln("R:1 R:2 C4:4 C4:4 C4:4 B3:d2 R:1 R:1 R:2 C4:4 C4:4 C4:4 B3:d2 R:1"),   # 8 bar(s), 14 events
    "PHRASE_R": ln("C4:2 C4:4 B3:4 B3:1"),   # 2 bar(s), 4 events
    "REST6": ln("R:1 R:2 R:1 R:2 R:1 R:2 R:1 R:1 R:1 R:2 R:1 R:2 R:1 R:2"),   # 8 bar(s), 14 events
    "REST7": ln("R:1 R:1 R:1 R:2 R:1 R:2"),   # 4 bar(s), 6 events
    "REST8": ln("R:1 R:2 R:1"),   # 2 bar(s), 3 events
    "REST9": ln("R:1 R:1 R:4 R:1 R:2 R:1 R:4"),   # 4 bar(s), 7 events
    "REST10": ln("R:1 R:4 R:1 R:2"),   # 2 bar(s), 4 events
    "REST11": ln("R:1 R:4"),   # 1 bar(s), 2 events
    "REST12": ln("R:2"),   # 1 bar(s), 1 events
    "REST13": ln("R:1 R:1 R:1 R:2 R:1 R:2 R:1 R:2 R:1 R:1 R:1 R:2"),   # 8 bar(s), 12 events
    "REST14": ln("R:1 R:2 R:1 R:2 R:1 R:1"),   # 4 bar(s), 6 events
    "PEDAL12": ln("R:2 C4:4 C4:4"),   # 1 bar(s), 3 events
    "PHRASE_S": ln("C4:2 B3:2"),   # 1 bar(s), 2 events
    "PHRASE_T": ln("R:1 R:1 R:2 C4:4 C4:4 C4:4 B3:4 B3:2"),   # 4 bar(s), 8 events
    "PHRASE_U": ln("C4:4 B3:4 R:2"),   # 1 bar(s), 3 events
    "REST15": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
}

VOX_SCORE = [
    ("REST", 5), ("REST2", 1), ("REST3", 1), ("PHRASE_A", 1), ("PEDAL", 1), ("PHRASE_A", 1),
    ("PEDAL2", 1), ("PHRASE_A", 1), ("PHRASE_B", 2), ("PEDAL3", 1), ("PEDAL4", 1), ("PHRASE_C", 1),
    ("PHRASE_D", 1), ("PEDAL5", 1), ("REST2", 1), ("REST4", 1), ("REST3", 1), ("PEDAL6", 2),
    ("PEDAL", 1), ("PHRASE_E", 1), ("PEDAL2", 1), ("PHRASE_F", 1), ("PEDAL7", 1), ("PEDAL8", 1),
    ("PEDAL3", 1), ("PHRASE_A", 1), ("PHRASE_D", 1), ("PEDAL7", 1), ("PEDAL5", 1), ("PEDAL9", 1),
    ("PHRASE_G", 1), ("PHRASE_H", 1), ("PHRASE_I", 1), ("PHRASE_J", 1), ("PHRASE_K", 1), ("PHRASE_L", 1),
    ("REST2", 1), ("REST5", 1), ("REST", 1), ("REST2", 1), ("REST5", 1), ("PHRASE_C", 1),
    ("PEDAL3", 1), ("PEDAL10", 1), ("PEDAL2", 1), ("PHRASE_M", 1), ("PEDAL7", 1), ("PHRASE_N", 1),
    ("PEDAL3", 1), ("PEDAL6", 1), ("PEDAL7", 1), ("PHRASE_E", 1), ("PEDAL7", 1), ("PEDAL11", 1),
    ("PEDAL9", 1), ("PHRASE_O", 1), ("PHRASE_H", 1), ("PHRASE_I", 1), ("PHRASE_J", 1), ("PHRASE_P", 1),
    ("PHRASE_Q", 1), ("PHRASE_I", 1), ("PHRASE_J", 1), ("PHRASE_R", 1), ("REST6", 1), ("REST7", 1),
    ("REST8", 1), ("REST9", 1), ("REST8", 1), ("REST10", 1), ("REST11", 1), ("REST12", 1),
    ("REST13", 1), ("REST14", 1), ("REST", 1), ("PEDAL12", 1), ("PHRASE_S", 1), ("PHRASE_T", 2),
    ("REST4", 1), ("PEDAL12", 1), ("PHRASE_U", 1), ("REST4", 1), ("REST3", 1), ("PHRASE_R", 1),
    ("REST3", 1), ("PHRASE_P", 1), ("REST", 2), ("REST15", 1), ("REST2", 1), ("REST4", 1),
    ("REST3", 1),
]

# ===================== DRUMS blocks (drum-kit) =====================
DRUMS = {
    "REST": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "GROOVE_A": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:4 kick+hihat-open:4"),   # 2 bar(s), 9 events
    "GROOVE_B": ln(
        "kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:4 "
        "kick+crash:4 kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 "
        "snare+crash:4 kick+crash:4"),   # 4 bar(s), 18 events
    "GROOVE_C": ln("kick+crash:4 crash:4 snare+crash:4 crash:4"),   # 1 bar(s), 4 events
    "GROOVE_D": ln("kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:4 kick+hihat-open:4"),   # 1 bar(s), 5 events
    "GROOVE_E": ln(
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:4 kick+hihat-open:4"),   # 2 bar(s), 9 events
    "GROOVE_F": ln("kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_G": ln("kick+hihat-open:8 kick:8 snare:8 kick:8 snare:8 tom-low:8 tom-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_H": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+crash:8 kick:8 kick+crash:4 "
        "snare+crash:4 kick+crash:4"),   # 2 bar(s), 9 events
    "GROOVE_I": ln("kick+crash:8 kick:8 snare+crash:4 kick+crash:4 snare+crash:4"),   # 1 bar(s), 5 events
    "GROOVE_J": ln(
        "kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:4 "
        "kick+crash:4"),   # 2 bar(s), 9 events
    "GROOVE_K": ln("kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_L": ln("snare:8 kick:8 snare:8 tom-low:8 tom-low:8 tom-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_M": ln("kick+crash:4 hihat-open:4 snare+crash:4 hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_N": ln(
        "kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:4 kick+hihat-open:4 "
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 2 bar(s), 9 events
    "GROOVE_O": ln(
        "kick+crash:8 kick:8 kick+crash:4 snare+crash:4 snare+crash:4 kick+crash:4 crash:4 "
        "snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:4 kick+crash:4 "
        "kick+crash:4 crash:4 snare+crash:4 crash:4"),   # 4 bar(s), 18 events
    "GROOVE_P": ln(
        "kick+crash:8 kick:8 crash:8 kick:8 snare+crash:8 kick:8 snare:8 tom-low:T8 tom-low:T8 "
        "tom-low:T8"),   # 1 bar(s), 10 events
    "GROOVE_Q": ln("kick+tom-floor-low:1"),   # 1 bar(s), 1 events
    "GROOVE_R": ln("R:1 R:1 R:1 kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 4 bar(s), 7 events
    "GROOVE_S": ln(
        "kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4 "
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4 kick+hihat-open:4 hihat-open:4 "
        "snare+hihat-open:4 hihat-open:4"),   # 4 bar(s), 20 events
    "GROOVE_T": ln("kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4"),   # 1 bar(s), 6 events
    "GROOVE_U": ln("kick+crash:8 kick:8 crash:8 kick:8 kick+crash:4 kick+crash:4"),   # 1 bar(s), 6 events
    "GROOVE_V": ln(
        "kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:8 "
        "kick:8 kick+crash:4"),   # 2 bar(s), 10 events
    "GROOVE_W": ln(
        "kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4 "
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 2 bar(s), 10 events
    "GROOVE_X": ln("snare:8 kick+crash:d4 snare:8 kick+crash:d4"),   # 1 bar(s), 4 events
    "GROOVE_Y": ln("kick+crash:8 kick:8 crash:8 kick:8 snare+crash:4 crash:4"),   # 1 bar(s), 6 events
    "GROOVE_Z": ln("kick+crash:8 kick:8 kick+crash:4 snare+crash:8 kick:8 kick+crash:4"),   # 1 bar(s), 6 events
    "GROOVE_AA": ln("kick+crash:4 crash:4 snare+crash:4 crash:8 snare:16 snare:16"),   # 1 bar(s), 6 events
    "GROOVE_AB": ln("snare:8 snare:d4 snare:8 tom-low:8 tom-floor-low:4"),   # 1 bar(s), 5 events
    "GROOVE_AC": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4 kick+hihat-open:4 hihat-open:4 "
        "snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 kick+hihat-open:4 "
        "snare+hihat-open:8 kick:8 kick+hihat-open:4"),   # 4 bar(s), 20 events
    "GROOVE_AD": ln(
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4"),   # 2 bar(s), 10 events
    "GROOVE_AE": ln("kick+hihat-open:8 kick:8 kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:4"),   # 1 bar(s), 6 events
    "GROOVE_AF": ln("kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:4 hihat-open:8 kick:8"),   # 1 bar(s), 6 events
    "GROOVE_AG": ln(
        "snare:8 kick+crash:d4 snare:8 kick+crash:d4 kick+crash:4 hihat-open:4 snare+hihat-open:4 "
        "hihat-open:4"),   # 2 bar(s), 8 events
    "GROOVE_AH": ln(
        "kick+crash:8 kick:8 kick+crash:4 snare+crash:4 kick+crash:4 kick+crash:4 crash:4 "
        "snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:4 snare+crash:4 "
        "kick+crash:4 crash:4 snare+crash:4 crash:4"),   # 4 bar(s), 18 events
    "GROOVE_AI": ln(
        "kick+crash:8 kick:8 kick+crash:4 snare+crash:4 kick+crash:4 kick+crash:4 crash:4 "
        "snare+crash:4 crash:4"),   # 2 bar(s), 9 events
    "GROOVE_AJ": ln("kick+crash:8 kick:8 kick+crash:4 snare:16 snare:16 tom-low:8 tom-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_AK": ln("kick+crash:8 kick:8 kick+crash:4 snare:8 tom-low:8 snare:4"),   # 1 bar(s), 6 events
    "GROOVE_AL": ln("kick+crash:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 16 bar(s), 16 events
    "REST2": ln("R:1 R:1 R:1 R:1"),   # 4 bar(s), 4 events
    "REST3": ln("R:1 R:2"),   # 1 bar(s), 2 events
    "GROOVE_AM": ln("kick+crash:1 R:1 R:2 kick+crash:2 R:1"),   # 4 bar(s), 5 events
    "REST4": ln("R:1"),   # 1 bar(s), 1 events
    "GROOVE_AN": ln("kick+crash:8 kick+crash:8 kick+crash:d2"),   # 1 bar(s), 3 events
    "REST5": ln("R:1 R:1 R:1 R:1 R:1 R:1 R:1 R:1"),   # 8 bar(s), 8 events
    "REST6": ln("R:1 R:1"),   # 2 bar(s), 2 events
    "GROOVE_AO": ln("kick+crash:8 kick+crash:8 kick+crash:1 kick+crash:4"),   # 1 bar(s), 4 events
    "GROOVE_AP": ln(
        "kick+hihat-open:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:8 kick:8 kick+hihat-open:4 kick+hihat-open:4 hihat-open:4 "
        "snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 kick+hihat-open:4 "
        "snare+hihat-open:8 kick:8 kick+hihat-open:4"),   # 4 bar(s), 20 events
    "GROOVE_AQ": ln("kick+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 5 events
    "GROOVE_AR": ln("kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:4 kick+crash:4"),   # 1 bar(s), 5 events
    "GROOVE_AS": ln("kick+crash:8 kick:8 kick+crash:8 snare:8 snare:8 tom-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_AT": ln(
        "kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 snare+crash:4 "
        "snare+crash:4 kick+crash:4 crash:4 snare+crash:4 crash:4 kick+crash:8 kick:8 kick+crash:4 "
        "snare+crash:4 kick+crash:4"),   # 4 bar(s), 18 events
    "GROOVE_AU": ln(
        "kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 snare+crash:2 kick+crash:8 "
        "kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 snare+crash:2"),   # 4 bar(s), 14 events
    "GROOVE_AV": ln("kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 snare+crash:2"),   # 2 bar(s), 7 events
    "GROOVE_AW": ln("kick+crash:8 kick:d4 snare+crash:4 snare+crash:4"),   # 1 bar(s), 4 events
    "GROOVE_AX": ln(
        "kick+crash:2 snare+crash:2 kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 "
        "snare+crash:2 kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4"),   # 4 bar(s), 14 events
    "GROOVE_AY": ln("kick+crash:2 snare+crash:2 kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4"),   # 2 bar(s), 7 events
    "GROOVE_AZ": ln("kick+crash:2 snare+crash:2"),   # 1 bar(s), 2 events
    "GROOVE_BA": ln(
        "kick+tom-floor-low:8 kick+tom-floor-low:8 kick+tom-floor-low:4 kick+tom-floor-low:4 "
        "kick+tom-floor-low:4"),   # 1 bar(s), 5 events
    "GROOVE_BB": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8 snare+hihat-open:4 "
        "snare+hihat-open:4"),   # 1 bar(s), 7 events
    "GROOVE_BC": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8 snare:8 tom-low:8 tom-low:4"),   # 1 bar(s), 8 events
    "GROOVE_BD": ln(
        "kick+crash:4 ride:4 snare+ride:4 ride:8 snare:16 snare:16 snare:8 tom-low:8 tom-low:8 "
        "tom-low:8"),   # 1 bar(s), 10 events
    "GROOVE_BE": ln("kick+crash:4 ride:4 snare+ride:4 ride:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_BF": ln("tom-low:8 kick:8 tom-low:8 tom-low:8 tom-low:8 tom-low:8 tom-low:8 tom-low:8"),   # 1 bar(s), 8 events
    "GROOVE_BG": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8 snare:4 tom-low:8 tom-low:8"),   # 1 bar(s), 8 events
    "GROOVE_BH": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8 snare:4 tom-low:4"),   # 1 bar(s), 7 events
    "GROOVE_BI": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_BJ": ln(
        "snare+tom-floor-low:8 snare+tom-floor-low:8 snare+tom-floor-low:8 snare+tom-floor-low:8 "
        "snare+tom-floor-low:8 snare+tom-floor-low:8 snare+tom-floor-low:8 snare+tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_BK": ln("kick+crash:4 crash:4 snare+crash:4 kick+crash:8 kick:8 snare+crash:4 snare+crash:4"),   # 1 bar(s), 7 events
    "GROOVE_BL": ln("kick+crash:4 crash:4 snare+crash:4 crash:8 kick:8 snare+crash:8 snare:8 kick+crash:4"),   # 1 bar(s), 8 events
    "GROOVE_BM": ln("kick+crash:4 crash:4 snare+crash:4 kick+crash:8 kick:8 snare+crash:4 kick+crash:4"),   # 1 bar(s), 7 events
    "GROOVE_BN": ln("kick+crash:4 crash:4 snare+crash:4 crash:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_BO": ln("snare:8 kick:8 tom-floor-low+tom-low:8 kick:8 tom-floor-low+tom-low:8 kick+crash:d4"),   # 1 bar(s), 6 events
    "GROOVE_BP": ln("kick+crash:4 crash:4 snare+crash:4 kick+crash:8 kick:8 snare+crash:4"),   # 1 bar(s), 6 events
    "GROOVE_BQ": ln(
        "kick+crash:4 kick+crash:4 crash:4 snare+crash:4 crash:8 kick:8 snare:8 tom-low:T8 tom-low:T8 "
        "tom-low:T8"),   # 1 bar(s), 10 events
    "GROOVE_BR": ln("kick:4 kick+crash:4 crash:4 snare+crash:4 kick+crash:8 kick:8"),   # 1 bar(s), 6 events
    "GROOVE_BS": ln(
        "snare+crash:8 snare:8 kick+crash:4 kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:8 "
        "kick:8"),   # 1 bar(s), 8 events
    "GROOVE_BT": ln(
        "snare:4 snare:8 tom-low:T8 tom-low:T8 tom-low:T8 kick:8 tom-low:8 tom-low:T8 tom-low:T8 "
        "tom-low:T8 kick:8"),   # 1 bar(s), 11 events
    "GROOVE_BU": ln("kick+crash:4 hihat-open:4 snare+crash:4 kick+hihat-open:8 kick:8 snare+hihat-open:4"),   # 1 bar(s), 6 events
    "GROOVE_BV": ln(
        "kick+crash:8 kick+crash:8 kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 "
        "kick:8 snare+hihat-open:8 snare:8"),   # 1 bar(s), 9 events
    "GROOVE_BW": ln("kick+crash:4 kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8"),   # 1 bar(s), 6 events
    "GROOVE_BX": ln("kick+crash:4 kick+crash:4"),   # 1 bar(s), 2 events
    "GROOVE_BY": ln("snare+crash:4 snare+crash:4 tom-floor-low+tom-low:8 kick+crash:d4"),   # 1 bar(s), 4 events
    "GROOVE_BZ": ln(
        "kick+crash:4 crash:4 snare+crash:4 kick+crash:8 kick:8 snare:8 tom-low:T8 tom-low:T8 "
        "tom-low:T8 kick:4"),   # 1 bar(s), 10 events
    "GROOVE_CA": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8 snare+hihat-open:4 "
        "snare+hihat-open:4"),   # 1 bar(s), 7 events
    "GROOVE_CB": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8"),   # 1 bar(s), 5 events
    "GROOVE_CC": ln("snare+hihat-open:8 kick:8 tom-low+hihat-open:8 kick:8 tom-floor-low:8 kick+crash:d4"),   # 1 bar(s), 6 events
    "GROOVE_CD": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8 snare+crash:4 "
        "kick+crash:4"),   # 1 bar(s), 7 events
    "GROOVE_CE": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8 snare:8 snare:8 "
        "tom-low:16 tom-low:16 tom-low:16 tom-low:16"),   # 1 bar(s), 11 events
    "GROOVE_CF": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 kick+hihat-open:8 kick:8 snare+crash:4 "
        "snare+crash:4"),   # 1 bar(s), 7 events
    "GROOVE_CG": ln(
        "kick+tom-floor-low:8 kick+tom-floor-low:8 kick+tom-floor-low:4 kick+tom-floor-low:8 "
        "kick+tom-floor-low:d4"),   # 1 bar(s), 5 events
    "GROOVE_CH": ln("R:1 kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 2 bar(s), 5 events
    "GROOVE_CI": ln("kick+hihat-open:8 kick:8 kick+hihat-open:4 snare+hihat-open:4 snare+hihat-open:4"),   # 1 bar(s), 5 events
    "GROOVE_CJ": ln(
        "kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4 kick+hihat-open:8 kick:8 "
        "kick+hihat-open:4 snare+hihat-open:4 kick+crash:4"),   # 2 bar(s), 9 events
    "GROOVE_CK": ln("kick+hihat-open:4 hihat-open:8 kick:8 snare+hihat-open:8 kick:8 hihat-open:8 kick:8"),   # 1 bar(s), 7 events
    "GROOVE_CL": ln(
        "snare:8 tom-low:T8 tom-low:T8 tom-floor-low:T8 kick:8 snare+crash:8 kick:8 "
        "tom-floor-low+tom-low:8 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8"),   # 1 bar(s), 10 events
    "GROOVE_CM": ln("kick+crash:4 hihat-open:4 snare+hihat-open:4 hihat-open:4"),   # 1 bar(s), 4 events
    "GROOVE_CN": ln("kick+crash:8 kick:8 kick+crash:4 snare+crash:4 snare+crash:4"),   # 1 bar(s), 5 events
    "GROOVE_CO": ln("snare:8 snare:8 snare:8 tom-low:8 tom-low:8 tom-low:8 tom-floor-low:8 tom-floor-low:8"),   # 1 bar(s), 8 events
    "GROOVE_CP": ln("kick+crash:8 kick:8 kick+crash:4 snare+crash:4 snare+crash:8 kick:8"),   # 1 bar(s), 6 events
    "GROOVE_CQ": ln("kick+crash:8 kick+crash:4 kick+crash:8 kick+crash:4 hihat-open:8 kick:8"),   # 1 bar(s), 6 events
    "GROOVE_CR": ln("snare:8 kick:8 snare:8 snare:8 kick:8 snare:8 snare:8 kick:8"),   # 1 bar(s), 8 events
    "GROOVE_CS": ln(
        "kick+crash:2 snare+crash:2 kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 "
        "snare+crash:2 kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 snare+crash:2 "
        "kick+crash:8 kick:8 kick:4 snare+crash:4 kick:4 kick+crash:2 snare+crash:2 kick+crash:8 "
        "kick:8 kick:4 snare+crash:8 tom-floor-low+tom-low:8 tom-floor-low+tom-low:8 "
        "tom-floor-low+tom-low:8"),   # 8 bar(s), 30 events
    "GROOVE_CT": ln("kick+crash:2 snare+crash:d4 kick:8"),   # 1 bar(s), 3 events
    "GROOVE_CU": ln(
        "kick+snare+tom-floor-low:8 kick+snare+tom-floor-low:8 kick+snare+tom-floor-low:4 "
        "kick+tom-floor-low+tom-low:4 kick+tom-floor-low+tom-low:4"),   # 1 bar(s), 5 events
}

DRUMS_SCORE = [
    ("REST", 3), ("GROOVE_A", 1), ("GROOVE_B", 1), ("GROOVE_C", 1), ("GROOVE_D", 1), ("GROOVE_A", 1),
    ("GROOVE_E", 2), ("GROOVE_F", 1), ("GROOVE_G", 1), ("GROOVE_H", 1), ("GROOVE_C", 1), ("GROOVE_I", 1),
    ("GROOVE_J", 1), ("GROOVE_K", 1), ("GROOVE_L", 1), ("GROOVE_M", 1), ("GROOVE_N", 1), ("GROOVE_O", 1),
    ("GROOVE_P", 1), ("GROOVE_Q", 1), ("GROOVE_R", 1), ("GROOVE_S", 1), ("GROOVE_T", 1), ("GROOVE_C", 1),
    ("GROOVE_U", 1), ("GROOVE_V", 1), ("GROOVE_C", 1), ("GROOVE_W", 1), ("GROOVE_T", 1), ("GROOVE_K", 1),
    ("GROOVE_X", 1), ("GROOVE_V", 2), ("GROOVE_Y", 1), ("GROOVE_Z", 1), ("GROOVE_AA", 1), ("GROOVE_AB", 1),
    ("GROOVE_AC", 1), ("GROOVE_AD", 1), ("GROOVE_F", 1), ("GROOVE_AE", 1), ("GROOVE_AC", 1), ("GROOVE_AD", 1),
    ("GROOVE_AF", 1), ("GROOVE_AG", 1), ("GROOVE_AH", 1), ("GROOVE_AI", 1), ("GROOVE_AJ", 1), ("GROOVE_B", 1),
    ("GROOVE_J", 1), ("GROOVE_C", 1), ("GROOVE_AK", 1), ("GROOVE_AL", 1), ("REST2", 1), ("REST3", 1),
    ("GROOVE_AM", 1), ("REST4", 1), ("GROOVE_AN", 1), ("REST5", 1), ("REST6", 1), ("GROOVE_AM", 1),
    ("REST4", 1), ("GROOVE_AO", 1), ("GROOVE_AC", 1), ("GROOVE_AP", 1), ("GROOVE_AC", 1), ("GROOVE_AD", 1),
    ("GROOVE_AQ", 1), ("GROOVE_AG", 1), ("GROOVE_AR", 1), ("GROOVE_B", 1), ("GROOVE_C", 1), ("GROOVE_AS", 1),
    ("GROOVE_J", 1), ("GROOVE_AT", 1), ("GROOVE_J", 1), ("GROOVE_C", 1), ("GROOVE_AU", 1), ("GROOVE_AV", 1),
    ("GROOVE_AW", 1), ("GROOVE_AX", 1), ("GROOVE_AY", 1), ("GROOVE_AZ", 1), ("GROOVE_BA", 1), ("GROOVE_BB", 1),
    ("GROOVE_BC", 1), ("GROOVE_BD", 1), ("GROOVE_BE", 1), ("GROOVE_BF", 1), ("GROOVE_BG", 2), ("GROOVE_BH", 1),
    ("GROOVE_BI", 1), ("GROOVE_BJ", 1), ("GROOVE_BK", 1), ("GROOVE_BL", 1), ("GROOVE_BM", 1), ("GROOVE_BN", 1),
    ("GROOVE_BO", 1), ("GROOVE_BP", 1), ("GROOVE_BQ", 1), ("GROOVE_BR", 1), ("GROOVE_BS", 1), ("GROOVE_BT", 1),
    ("GROOVE_BU", 1), ("GROOVE_BV", 1), ("GROOVE_BW", 1), ("GROOVE_BX", 1), ("GROOVE_BI", 1), ("GROOVE_BY", 1),
    ("GROOVE_BK", 1), ("GROOVE_BZ", 1), ("GROOVE_CA", 1), ("GROOVE_CB", 1), ("GROOVE_CC", 1), ("GROOVE_CD", 1),
    ("GROOVE_CE", 1), ("GROOVE_CF", 1), ("GROOVE_BI", 1), ("GROOVE_CG", 1), ("GROOVE_AL", 1), ("GROOVE_CH", 1),
    ("GROOVE_CI", 1), ("GROOVE_CJ", 1), ("GROOVE_A", 1), ("GROOVE_CK", 1), ("GROOVE_CL", 1), ("GROOVE_CM", 1),
    ("GROOVE_CN", 1), ("GROOVE_BN", 1), ("GROOVE_CO", 1), ("GROOVE_C", 1), ("GROOVE_CP", 1), ("GROOVE_CQ", 1),
    ("GROOVE_CR", 1), ("GROOVE_CS", 3), ("GROOVE_AX", 1), ("GROOVE_AY", 1), ("GROOVE_CT", 1), ("GROOVE_CU", 1),
    ("GROOVE_AL", 1), ("REST2", 1),
]


# =========================== arrangement / plumbing ===========================
LANES = ('lead', 'rhythm', 'bass', 'vox', 'drums')
INSTRUMENTS = {
    "lead": "distortion-guitar",
    "rhythm": "distortion-guitar",
    "bass": "electric-bass-pick",
    "vox": "tenor-sax",
    "drums": "drum-kit",
}
BLOCKS = {
    "lead": LEAD,
    "rhythm": RHYTHM,
    "bass": BASS,
    "vox": VOX,
    "drums": DRUMS,
}
SONG_MAPS = {
    "lead": LEAD_SCORE,
    "rhythm": RHYTHM_SCORE,
    "bass": BASS_SCORE,
    "vox": VOX_SCORE,
    "drums": DRUMS_SCORE,
}

TEMPO_MAP = [
    {"beat": 0, "bpm": 128},
    {"beat": 64, "bpm": 125},
    {"beat": 68, "bpm": 126},
    {"beat": 72, "bpm": 125},
    {"beat": 76, "bpm": 126},
    {"beat": 80, "bpm": 125},
    {"beat": 84, "bpm": 126},
    {"beat": 88, "bpm": 127},
    {"beat": 92, "bpm": 126},
    {"beat": 96, "bpm": 125},
    {"beat": 100, "bpm": 126},
    {"beat": 104, "bpm": 125},
    {"beat": 108, "bpm": 126},
    {"beat": 112, "bpm": 128},
    {"beat": 116, "bpm": 126},
    {"beat": 560, "bpm": 116},
    {"beat": 580, "bpm": 125},
    {"beat": 924, "bpm": 110},
    {"beat": 928, "bpm": 105},
    {"beat": 946, "bpm": 107},
    {"beat": 1006, "bpm": 102},
    {"beat": 1110, "bpm": 132},
    {"beat": 1366, "bpm": 110},
]

# Rebuild every lane from its song map; all lanes span the same bars, so they share
# one total length (asserted below) -- no manual rest-padding needed.
timeline = {lane: expand(BLOCKS[lane], SONG_MAPS[lane]) for lane in LANES}

composition = {
    "title": "Monolord - Empress Rising - IA full Drums (Recreation)",
    "bpm": 128,
    "time_signature": "4/4",
    "tempo_map": TEMPO_MAP,
    "tracks": [
        {"instrument": INSTRUMENTS[lane], "notes": timeline[lane]} for lane in LANES
    ],
}


if __name__ == "__main__":
    total = beats(timeline[LANES[0]])
    for lane in LANES:
        assert abs(beats(timeline[lane]) - total) < 1e-6, \
            f"{lane} misaligned ({beats(timeline[lane])} vs {total})"
    print(f"Title : Monolord - Empress Rising - IA full Drums (Recreation)")
    print(f"Lanes : {', '.join(LANES)}")
    print(f"Length: {total:.0f} beats")
    print("Blocks: " + ", ".join(f"{l}={len(BLOCKS[l])}" for l in LANES))
    nev = sum(len(t["notes"]) for t in composition["tracks"])
    print(f"Events: {nev} notes/chords across {len(composition['tracks'])} tracks")
    path = generate_midi_from_dict(composition)
    print(f"MIDI written: {path}")
    stem = Path(path).stem
    print(f'Render to WAV:  python render_wav.py 0.7 "{stem}"')
